### ISSUE TITLE
CMake Error in nvJPEG

### ISSUE THREAD

**Issue by OpenDGPS** [NVIDIA/CUDALibrarySamples#1]
CMake Error: The source directory "<...>/CUDALibrarySamples/nvJPEG" does not appear to contain CMakeLists.txt.

Additionally NvElement.h is missing in NvJpegDecoder.h

**Comment by maheshkha** [comment]
nvJPEG decoder sample CMakeLists.txt located here "<...>/CUDALibrarySamples/nvJPEG/nvJPEG-Decoder"

Can you provide additional information.

**Comment by OpenDGPS** [comment]
According to README.md in /CUDALibrarySamples/nvJPEG/nvJPEG-Decoder I need to 

```
$ mkdir build
$ cd build
$ cmake ..
$ make
```

I'm trying to do this on a Jetson Xavier, drivers and CUDA SDK up and running but getting an error if I run ```cmake ..``` saying:

```
CMake Error: The source directory "<...>CUDALibrarySamples/nvJPEG" does not appear to contain CMakeLists.txt.
```

**Comment by maheshkha** [comment]
Currently nvJPEG library does not support Jetson Xavier and L4T drivers. 
We are planning that feature in future CUDA release.

**Comment by ZGarfield** [comment]
Hi I want to know the nvJPEG library still does not support Jetson Xavier and L4T drivers, now?

**Comment by maheshkha** [comment]
> Hi I want to know the nvJPEG library still does not support Jetson Xavier and L4T drivers, now? And CUDA10.2 can support it?

Please refer this example https://docs.nvidia.com/jetson/l4t-multimedia/l4t_mm_06_jpeg_decode.html

**Comment by ZGarfield** [comment]
> > Hi I want to know the nvJPEG library still does not support Jetson Xavier and L4T drivers, now? And CUDA10.2 can support it?
> 
> Please refer this example https://docs.nvidia.com/jetson/l4t-multimedia/l4t_mm_06_jpeg_decode.html

Thanks for the Reply.
