### ISSUE TITLE
Compile error in ubuntu machine

### ISSUE THREAD

**Issue by Huangyuren** [NVIDIA/CUDALibrarySamples#10]
Unable to make.
My machine info:
OS: Ubuntu 18.04 LTS
CPU: i7-5930K
GPU: RTX 2080 Ti, driver version: 455.23.05, CUDA version: 11.0 (also have tried 10.1, 10.0 on same machine and all failed)
Screen snapshot provided as below:
<img width="1039" alt="Screen Shot 2020-11-03 at 5 10 27 PM" src="https://user-images.githubusercontent.com/37345266/97969706-65fcdf80-1dfb-11eb-9ff1-ed35365146c5.png">
and error messages after make cammand:
<img width="1260" alt="Screen Shot 2020-11-03 at 5 35 19 PM" src="https://user-images.githubusercontent.com/37345266/97969715-6a28fd00-1dfb-11eb-8dbb-b4e811fa8566.png">

Thanks!

**Comment by maheshkha** [comment]
Hello,

Please do following the steps :
1. Download and install [CUDA Toolkit 11.0](https://developer.nvidia.com/cuda-11.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804) 
2. Pull out the [nvJPEG decoder code](https://github.com/NVIDIA/CUDALibrarySamples/tree/master/nvJPEG/nvJPEG-Decoder)
3. set the environment variables 
`
export PATH=$PATH:/usr/local/cuda-11.0/bin
export CUDADIR=/usr/local/cuda-11.0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.0/lib64

`
4. Make build directory and cmake ..

`
cmake ..
-- The CUDA compiler identification is NVIDIA 11.0.184
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CUDA compiler: /usr/local/cuda-11.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-11.0/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done

-- Build files have been written to: /home/user/project/cudalibrarysamples-mirror/nvJPEG/nvJPEG-Decoder/build
`
5. make
`
Scanning dependencies of target nvjpegDecoder
[ 50%] Building CUDA object CMakeFiles/nvjpegDecoder.dir/nvjpegDecoder.cpp.o
[100%] Linking CUDA executable nvjpegDecoder
[100%] Built target nvjpegDecoder

`

We have tested nvJPEG decoder locally with Ubuntu 18.04 and CUDA 11.0, no issues found.

CUDA 10.1 and CUDA 10.2 - some features are not supported.

**Comment by Huangyuren** [comment]
Many thanks for your prompt reply. This works well on my machine (CUDA 11.0 & Ubuntu 18.04).
