### ISSUE TITLE
Is there any way to make nvjpeg encode more fast?

### ISSUE THREAD

**Issue by Bryan2Lee** [NVIDIA/CUDALibrarySamples#105]
1. Now we are using nvjpeg library to do jpeg compressions with (Tesla T4 GPU), hoping that the compression takes less time than using cpu.
2. If the picture is big enough, such as 4k or 1080p, than the nvjpeg(gpu) uses much less than cpu, but if the picture is not too big, such as 64 * 64 or 352 * 64, the gpu takes more time than cpu.
the average time of encoding one 64 * 64 image is 1 millisecond, the cpu only takes 200 microsecond to encode a 64 * 64 image.
sometimes, the gpu even takes more 5 millisecond to encode a 64 * 64 image
3. why is that? How to fix this?

**Comment by maheshkha** [comment]
Hi @Bryan2Lee 

Thank you for reporting this issue.
If you set the encoder quality and turn off optimized huffman, then small size image overall performance will improve but at small percentage. 

Example API
CHECK_NVJPEG(nvjpegEncoderParamsSetQuality(nvjpeg_encode_params, 75, NULL));
CHECK_NVJPEG(nvjpegEncoderParamsSetOptimizedHuffman(nvjpeg_encode_params, 0, NULL));

Raw image data copy from Host to GPU is limiting some of encoding stages - it will benefits more for large image size.
