### ISSUE TITLE
cuSPARSELt/spmma and CUDA 12

### ISSUE THREAD

**Issue by rjfnobre** [NVIDIA/CUDALibrarySamples#114]
Is "cuSPARSELt/spmma" supposed to work with CUDA 12?

In a machine with CUDA 12 installed, I get a warning stating that libcudart.so.11.0 has not been found, followed by undefined references to many libcudart.so.11.0 functions.

**Comment by fbusato** [comment]
cuSPARSELt doesn't support CUDA 12.x yet. This feature should be part of the next release.
