### ISSUE TITLE
nvJPEG raises SIGSEGV while decoding some broken images with EXIF tags while parsing their headers

### ISSUE THREAD

**Issue by dev0x13** [NVIDIA/CUDALibrarySamples#116]
### Problematic images
![cat_invalid_num_of_exif_tags](https://user-images.githubusercontent.com/5624568/226876348-ddac6d67-e71c-4aa0-bace-5594928583c0.jpg)
![invalid_exif_tag_data_type](https://user-images.githubusercontent.com/5624568/226876351-d95f9845-dbf4-4157-b00e-5e1a0f0eb74f.jpg)
### Steps to reproduce
1. Build the `nvjpegDecoder` sample.
2. Run the sample with provided images.
I was able to reproduce this segfault using nvJPEG/CUDA 11.6-12.1.

**Comment by trybicki-nv** [comment]
The fix will be available in Cuda Toolkit 12.2u2 and 12.3

**Comment by trybicki-nv** [comment]
Closing.
