### ISSUE TITLE
Can multi streaming be used to improve jpeg encoding speed

### ISSUE THREAD

**Issue by simpia** [NVIDIA/CUDALibrarySamples#119]
I want to encode multiple images simultaneously. I use multiple streams on thr function nvjpegEncodeImage. But the encoding time is same to single stream. Why is this?

**Comment by zohebk-nv** [comment]
A significant part of the encoding pipeline is synchronous with respect to the host. Additional cuda streams alone may not help. Using multiple CPU threads and cuda streams may help improve encoding speed.

**Comment by trybicki-nv** [comment]
Closing. Feel free to reopen if more clarification is needed.
