### ISSUE TITLE
How to process the nvjpeg_t.channel{0,1,2...} in CUDA kernel function.

### ISSUE THREAD

**Issue by Alfons0329** [NVIDIA/CUDALibrarySamples#12]
Hello, I have a question about how we can process the object of channels{0, 1, 2...}  nvjpegImage_t

I have read [this doc](https://docs.nvidia.com/cuda/archive/10.0/nvjpeg/nvjpeg-type-declarations.html) and [this doc](https://docs.nvidia.com/cuda/archive/10.0/nvjpeg/using-nvjpeg-api.html#nvjpeg-single-image-decoding) about the underlying objects in nvjpegImage_t.

It is obvious that channel 0, 1, 2 represents the R G B channel according to line 146 in nvjpegDecoder.cpp and line 407 in nvjpegDecoder.h.

But when I try to perform a simple CUDA function as shown below, it immediately crash, and what's even worse is that my printf debugging log did not shown.

* CUDA kernel
```cpp
__global__ void simple_kernel_function_RGB(unsigned char* img_R, unsigned char* img_G, unsigned char* img_B, const int& img_row, const int& img_col){
    printf("CUDA kernel function, img_row %d img_col %d \n", img_row, img_col);
    for(int i = 0; i < img_row; i++){
        for(int j = 0; j < img_col; j++){
            printf("[KERNEL]: Access i %d j %d \n", i, j);
            img_R[i * img_col + j] = 0;
            img_G[i * img_col + j] = 255;
            img_B[i * img_col + j] = 255;
        }
    }
}
```

* Arguments passing
```cpp
if(params.fmt == NVJPEG_OUTPUT_RGB){
            img_R = iout[batch].channel[0];
            img_G = iout[batch].channel[1];
            img_B = iout[batch].channel[2];
            printf("RGB image! \n");
            if(!img_R || !img_G || !img_B){
                fprintf(stderr, "%s", "Nullpointerexception \n");
            }
            simple_kernel_function_RGB<<<1, 1>>>(img_R, img_G, img_B, img_row, img_col);
            printf("Finished GPU kernel call \n");
```

![image](https://user-images.githubusercontent.com/22470089/100568501-58594d80-3306-11eb-88f2-881de56c9e1c.png)
![image](https://user-images.githubusercontent.com/22470089/100568986-a753b280-3307-11eb-841b-decd87328ae0.png)

I have used "cuda-memcheck" to verify where I got wrong and it says I have an invalid address read. (If the CUDA kernel function call is removed, then everything works fine again)

```
at 0x00000070 in simple_kernel_function_RGB(unsigned char*, unsigned char*, unsigned char*, int const &, int const &)
=========     by thread (0,0,0) in block (0,0,0)
=========     Address 0x7ffecf8df618 is out of bounds
```

## And here goes my questions
* Q1: Is it possible to directly operate the pointer in nvjpegImage_t, for example in nvjpedDecode.cpp , 
```
iout.channel[0][0] = 0
iout.channel[1][0] = 0
iout.channel[2][0] = 0
```
Describes to make the RGB value in pixel 0 to ber 0
Or we have to use cuda kernel call `<<<>>>` to operate the pointer data in GPU

* Q2: From Q1, my case it is not workable, or does some pre-setup for operating the nvjpegImage_t is required ( I think cudaMemcpy(D2H) should not be used since nvjpeg directly decode image in GPU, providing with great performance and throughput, suppose we move the data back to CPU pand process it, the advantage will lose.)

* Q3: Could the problem be my unsupported hardware since it says 
![image](https://user-images.githubusercontent.com/22470089/100568590-8e96cd00-3306-11eb-8ea5-bd586ca1ffd5.png)
in the very beginning.

HW Specs:
CPU: i9-9900K, GPU: TITAN V
OS: Ubuntu 18.04.3 LTS, Kernel version is 5.4.0-53-generic
NVIDIA-SMI: 455.38 (CUDA Version 11.1)
nvcc: 

Makefile:
```makefile
#---------------------------Required files-----------------------#
SRC=./src/
BIN=./bin/

SOURCE=$(SRC)main.cu
TARGET=$(BIN)main_out

#------------------------Compiler and flag-----------------------#
# Compilers
CC=nvcc
# CC= g++

# Libraries and flags
OPENCV_LIBS=`pkg-config --cflags --libs opencv`
LDFLAGS=-L../lib64 -L/usr/local/cuda-11.1/lib64
INCLUDES=-I./include -I/usr/local/cuda-11.1/include
LIBS=-ldl -lrt -lcudart -lnvjpeg
RPATH=-Wl,-rpath=../lib64 -Wl,-rpath=/usr/local/cuda-11.1/lib64
CXXFLAGS:= -O2 -std=c++14 $(LDFLAGS) $(INCLUDES) $(LIBS) #$(RPATH)

#---------------------------Rules-------------------------------#
all: cuda

cuda: $(SOURCE)  
	$(CC) -m64 $(SOURCE) $(CXXFLAGS) -o $(TARGET)

.PHONY: clean

clean:
	rm -f $(BIN)*.o
```

Where main.cu is just renamed of nvJpegDecoder.cpp and with my CUDA kernel and simple self-written functions mentioned above.

Sorry about the long problems because my research project need this library.
Many thanks to any advice in advance!

With regards,
Alfons

**Comment by maheshkha** [comment]
Hi,
Q1 Ans: No, You are trying to write on device memory from host (CPU) code.
Q2 Ans: If you want to check input or output images better to transfer to host (CPU) then display the image pixel values.
Q3 Ans: NVIDIA GPU A100 has dedicated JPEG decoding engine. You can refer the [nvJPEG blog](https://developer.nvidia.com/blog/leveraging-hardware-jpeg-decoder-and-nvjpeg-on-a100/) 

If you share your code will take a look how the kernel call make and memory checks.
