### ISSUE TITLE
NVJPEG failure: '#8' NVJPEG2K_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by ysfu86** [NVIDIA/CUDALibrarySamples#122]
this jp2 file have the same header information with issue #70 , version 0.7 can successfully decode the image of issue #70 , but just can't decode the bellow, maybe I should add the two kinds of jp2 file in issue #70 .
[error.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/11291494/error.zip)

**Comment by zohebk-nv** [comment]
Thank you reporting this issue. The attached bitstreams have COM marker in tile header which nvjpeg2k 0.7 does not support. The next release will have the fix for this

**Comment by ysfu86** [comment]
Is this problem solved?  Is there a new version released?

**Comment by ysfu86** [comment]
@trybicki-nv Is this problem solved? Is there a new version released?

**Comment by trybicki-nv** [comment]
Sorry, closed by accident. The issue will be fixed in the next release.

**Comment by ysfu86** [comment]
ok

> Sorry, closed by accident. The issue will be fixed in the next release.

**Comment by trybicki-nv** [comment]
The issue was solved in the latest release: nvJPEG2000 v0.7.5.
