### ISSUE TITLE
cuBLAS-GEMM，runtime_error

### ISSUE THREAD

**Issue by MalaJeans** [NVIDIA/CUDALibrarySamples#131]
When GEMM under Level-3 in cuBLAS is run, the following problem occurs：
A
1.00 3.00 
2.00 4.00 
=====
B
5.00 7.00 
6.00 8.00 
=====
CUDA error 222 at /home/gy/CUDALibrarySamples/cuBLAS/Level-3/gemm/cublas_gemm_example.cu:103
terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDA error
Aborted (core dumped)

How can I solve it ？thanks！

**Comment by kolbusa** [comment]
Apologies for a late response. The `222` error seems to mean that the PTX version is not compatible. Which GPU and which CUDA Toolkit version are you using?

**Comment by JanuszL** [comment]
Please reopen if this is still a valid issue for you.
