### ISSUE TITLE
Can't support hw decoding within Amazon EC2 H100(Lambda On-Demand Cloud)?

### ISSUE THREAD

**Issue by st7109** [NVIDIA/CUDALibrarySamples#132]
cuda version: 12.0

If i use “CUDALibrarySamples/nvJPEG/nvJPEG-Decoder“， when run that, it will notify the below info:
“”Hardware Decoder not supported. Falling back to default backend”

I want to confirm whether support JPEG decoding within Amazon EC2 H100 or not?

Thanks

**Comment by zohebk-nv** [comment]
H100 should have support for hardware decoder. 
Are observing the issue when running the sample as part of the docker container? If yes,  you can try including this option when initializing docker container: - --gpus '"capabilities=compute,utility,video"'

**Comment by trybicki-nv** [comment]
Closing. Feel free to re-open if more clarification is needed.
