### ISSUE TITLE
FP8 Example errors with different M,N and K

### ISSUE THREAD

**Issue by tbaruahghy** [NVIDIA/CUDALibrarySamples#135]
I was trying the LtFp8Matmul example on CUDA 12.1 H100 PCIe system. I was experimenting with different M,N and K values and there are random unexplained memory access errors. For example in one instance I kept my M as 4864 and N as 1536 and varied my K. When K =2048 the code works. However, whenever I try K values of 1024, 4096,8192 etc, the program crashes with "cuda API failed with status 700: an illegal memory access was encountered". I didn't change anything in the code apart from these values and the M,N and K dimensions I tried do follow the rules mentioned here(https://docs.nvidia.com/cuda/cublas/index.html#cublasltmatmul).  What is the issue behind the failure?. Thanks

**Comment by tbaruahghy** [comment]
Just wondering if anyone recognizes this issue as an inherent problem. Or is my choices of M,N and K inherently not compatible with FP8 support

**Comment by arkhodamoradi** [comment]
The code expects matrix A to be transposed ([link](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuBLASLt/LtFp8Matmul/sample_cublasLt_LtFp8Matmul.cu#L62)), however, as the leading dimension for A (lda), it passes m ([link](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuBLASLt/LtFp8Matmul/main.cpp#L49)). You may want to replace it with props.k
