### ISSUE TITLE
How long will cuSPARSELt to support TF32? Is there any sample codes of BF16?

### ISSUE THREAD

**Issue by linmuchuiyang** [NVIDIA/CUDALibrarySamples#14]
1. I checked the sample code of spMMA and read the reference of cuSPARSELt. According to the document, cuSPARSELt only supports FP16, BF16 and INT8. A100 has announced the TF32 could also utilize the sparsity of Tensor Core. How long will cuSPARSELt to support TF32?
2. BF16 is a new datatype for GPU,especially for Ampere. Is there any sample code that how we could use BF16 with cuSPARSELt?

**Comment by fbusato** [comment]
1. TF32 supports is planned, but I cannot provide a specific time frame. I will try to provide something more in the next days.
2. Modifying the example to support bfloat16 on Ampere should be straightforward. Just replace
    - `type  = CUDA_R_16F` with `type  = CUDA_R_16BF`
    - `__half` with `__nv_bfloat16`

**Comment by fbusato** [comment]
I can confirm that TF32 will be provided quite soon. Maybe already in the next release
