### ISSUE TITLE
CUDA version-cusparse

### ISSUE THREAD

**Issue by fatemeh9264** [NVIDIA/CUDALibrarySamples#142]
Hello
I want to use cusparse library in my project ; but I can not compile it. I don't know what s the problem? Is it for cuda version?
what is the least necessary version needed? I have the following error:
**gcc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by gcc)**

**Comment by qanhpham** [comment]
Probably your system is missing glibc 2.14.
Can you try `sudo apt-get update` or `apt-get install libc6` to see if it works?

**Comment by fatemeh9264** [comment]
It is the laboratory system, I don't have permission to run your command but as the administrator told me we guess it is related to cuda version. The installed version is less than 11. **what cuda version is necessary to use cuSPARSE?**

**Comment by qanhpham** [comment]
Your CUDA version is quite old. I suggest you to use version 11.x or, better, 12.x.

**Comment by fatemeh9264** [comment]
OK. Thanks a lot.
