### ISSUE TITLE
cusparseSpGEMM() won't work for alpha*op(A)*op(B) + beta*C = D

### ISSUE THREAD

**Issue by eattardo** [NVIDIA/CUDALibrarySamples#143]
It seems that cusparseSpGEMM() works only for alpha*op(A)*op(B) + beta*C = C' where C' and C have the **same** sparsity pattern (CSR format).

Does anyone have an idea of how to overcome the problem of the same pattern in C' and C and compute the general operation: alpha*op(A)*op(B) + beta*C = D?

**Comment by qanhpham** [comment]
Hi. You can so that by:

- setting beta = 0 to avoid the addition in SpGEMM
- using [csrgeam2](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-t-csrgeam2) to perform the addition operation between _alpha*op(A)op(B)_ and _betaC_.

**Comment by eattardo** [comment]
Thanks. I knew about csrgeam2() but I thought the cusparseSpGEMM was doing that.
