### ISSUE TITLE
sparse matrix transpose question

### ISSUE THREAD

**Issue by jinz2014** [NVIDIA/CUDALibrarySamples#149]
Is there a cuSparse function that transposes a sparse matrix in CSR to another one in CSR ?  Thanks.

Reference
https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2023-1/oneapi-mkl-sparse-omatcopy.html

**Comment by fbusato** [comment]
Yes, cuSPARSE provides `cusparseCsr2cscEx2()` https://docs.nvidia.com/cuda/cusparse/index.html#cusparsecsr2cscex2 to transpose a CSR matrix to CSC (which is CSR with columns/rows swapped).

**Comment by jinz2014** [comment]
I suppose that users need to convert the outputs in CSC to the outputs in CSR after calling cusparseCsr2cscEx2().  Thanks.

**Comment by jinz2014** [comment]
I have a follow-up question. Will cuSparse consider adding a function whose output is also in CSR format ?

**Comment by qanhpham** [comment]
Hi @jinz2014. Sorry, I don't get your question. A matrix in CSR is equivalent to its transposed matrix stored in CSC. You can think of the output of `cusparseCsr2cscEx2()` as a CSR matrix; then, this function acts as a transpose operation.

**Comment by qanhpham** [comment]
In the document, it is said that "The resulting matrix can also be seen as the transpose of the original sparse matrix."
Yes, I agree we should make it clearer that it's a transpose if we see the output as a CSR matrix.
