### ISSUE TITLE
nvJPEG encoder buffer size explode?

### ISSUE THREAD

**Issue by Huangyuren** [NVIDIA/CUDALibrarySamples#15]
Hi,
I have some questions regarding nvjpeg encoder calls.
Currently I am processing large scale whole slide images read from another library called Openslide; let's say the resolution is about 25000 * 15000 * 3(RGB). I found that _nvjpegEncodeImage()_ will throw either NVJPEG failure: '6' or NVJPEG failure: '5' depending on two different machine setup.

**Next,** to investigate the problem, I called _nvjpegEncodeGetBufferSize()_ to get roughly how much memory I may need. (Since error code 5 looks like memory allocator failure)

**Then** I found that once I gave $image_width, $image_height > 20000, the $max_stream_length will go to incredibly large value.
## Code
Details as comments
I followed this sample code at nvJPEG [official documentaion](https://docs.nvidia.com/cuda/nvjpeg/index.html#nvjpeg-encode-examples)

    nvjpegHandle_t nv_handle;
    nvjpegEncoderState_t nv_enc_state;
    nvjpegEncoderParams_t nv_enc_params;
    cudaStream_t stream;
    cudaStreamCreate(&stream);
     
    // initialize nvjpeg structures
    CHECK_NVJPEG(nvjpegCreateSimple(&nv_handle));
    CHECK_NVJPEG(nvjpegEncoderStateCreate(nv_handle, &nv_enc_state, stream));
    CHECK_NVJPEG(nvjpegEncoderParamsCreate(nv_handle, &nv_enc_params, stream));
    CHECK_NVJPEG(nvjpegEncoderParamsSetSamplingFactors(nv_enc_params, NVJPEG_CSS_444, stream));
    
    int64_t target_width, target_height;
    /* whole_slide_rgb is decalred as OpenCV's vector of matrix, i.e., vector<Mat>
    *  So we loop through this vector to sequentially fetch every RGB image for nvJPEG encoder
    */
    for(int idx=0; idx < whole_slide_rgb.size(); idx++){
        nvjpegImage_t nv_image;
        target_width = target_dimension[idx].first;
        target_height = target_dimension[idx].second;
        
        // Fill nv_image with image data, let’s say target_height, target_width image in RGB format
        Mat bgr[3];
        split(whole_slide_rgb[idx], bgr); // split RGB three channels from whole_slide_rgb[idx]
        printf("   Target width: %ld, Target height: %ld\n", target_width, target_height);
        for(int i=0; i<3; i++){
            CHECK_CUDA(cudaMalloc((void **)&(nv_image.channel[i]), target_width * target_height));
            CHECK_CUDA(cudaMemcpy(nv_image.channel[i], bgr[2-i].data, target_width * target_height, cudaMemcpyHostToDevice));
            nv_image.pitch[i] = (size_t)target_width;
        }
        
        /* Tricky part
        *  (target_width, target_height) real case, which is 25659 * 15781
        *  (25000, 15000) is close to my real image dimension, and it would output extraordinarily long length
        *  (15000, 15000) is for comparison, works fine and reasonable
        *  (10000, 10000) Also, works fine and reasonable.
        */
        size_t max_stream_length=0;
        CHECK_NVJPEG(nvjpegEncodeGetBufferSize(nv_handle, nv_enc_params, target_width, target_height, &max_stream_length));
        printf("   Max stream length estimated: %zu\n", max_stream_length);
        CHECK_NVJPEG(nvjpegEncodeGetBufferSize(nv_handle, nv_enc_params, 25000, 15000, &max_stream_length));
        printf("   Max stream length estimated: %zu\n", max_stream_length);
        CHECK_NVJPEG(nvjpegEncodeGetBufferSize(nv_handle, nv_enc_params, 15000, 15000, &max_stream_length));
        printf("   Max stream length estimated: %zu\n", max_stream_length);
        CHECK_NVJPEG(nvjpegEncodeGetBufferSize(nv_handle, nv_enc_params, 10000, 10000, &max_stream_length));
        printf("   Max stream length estimated: %zu\n", max_stream_length);
        // Compress image
        CHECK_NVJPEG(nvjpegEncodeImage(nv_handle, nv_enc_state, nv_enc_params,
            &nv_image, NVJPEG_INPUT_RGB, target_width, target_height, stream));
         
        // get compressed stream size
        size_t length;
        CHECK_NVJPEG(nvjpegEncodeRetrieveBitstream(nv_handle, nv_enc_state, NULL, &length, stream));
        // get stream itself
        cudaStreamSynchronize(stream);
        vector<unsigned char> jpeg(length);
        CHECK_NVJPEG(nvjpegEncodeRetrieveBitstream(nv_handle, nv_enc_state, jpeg.data(), &length, 0));
         
        // write stream to file
        const char* jpegstream = reinterpret_cast<const char*>(jpeg.data());
        cudaStreamSynchronize(stream);
        ofstream output_file("test"+to_string(idx)+".jpg", ios::out | ios::binary);
        output_file.write(jpegstream, length);
        output_file.close();
    }
    CHECK_NVJPEG(nvjpegDestroy(nv_handle));`

## Outputs
![image](https://user-images.githubusercontent.com/37345266/102922922-c938f300-44c9-11eb-954c-e71d3daa2ce6.png)
[Note]: Line 182 is exactly nvjpegEncodeImage right after checking for max buffer size
#### Self PC
* OS: Ubuntu 18.04
* host ram: 16GB ddr4
* nvcc --version: cuda_11.0
* GPU: RTX 2080Ti
* CPU: Intel i7-9700K
#### Super computer -- Taiwania-2
* OS: Ubuntu 18.04
* host ram: 754GB ddr4
* nvcc --version: cuda_11.1
* GPU: NVIDIA Tesla V100-SXM2 (32G)
* CPU: Intel(R) Xeon(R) Gold 6154

Thanks for your support!

**Comment by maheshkha** [comment]
Hello Yu-Jen Huang,
Thank you for reporting the issue. 
The problem occurred because of `size_t` data type - which overflow for large size of images. 
Max size for `size_t` 65535 that is reason image pitch calculation overflows the values.

We are looking for alternative approach line `cudaMallocPitch` to handle the memory allocations for large images.
Will keep you posted.

**Comment by avtomaton** [comment]
2 years since the issue was opened. Any update yet?

**Comment by trybicki-nv** [comment]
We have reduced memory requirements of nvJPEG. Can you please verify with the latest Cuda Toolkit?

**Comment by trybicki-nv** [comment]
No traction. Closing.
