### ISSUE TITLE
Deprecation warning of csric02Info_t with CUDA-12.3

### ISSUE THREAD

**Issue by jczhang07** [NVIDIA/CUDALibrarySamples#154]
Hello, 
We met these warnings with CUDA-12.3 but don't know what alternatives are available.

```
/usr/local/cuda-12.3/include/cusparse.h:434:1: warning: ‘csric02Info_t’ is deprecated: The type will be removed in the next major release [-Wdeprecated-declarations]
  434 | cusparseCreateCsric02Info(csric02Info_t* info);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by fbusato** [comment]
We don’t currently plan to support IC0 for the next major release. We haven’t found strong enough use cases to invest significant engineering effort and resources to maintain the feature.

**Comment by jczhang07** [comment]
I guess you also won't support ILU0 anymore?

**Comment by jczhang07** [comment]
BTW, do you have a timeline for the next major release (so we know when we have to change our software)?

**Comment by fbusato** [comment]
yes, the same for ILU0. Just to avoid confusion, we will keep the deprecated routines in case we find some relevant use cases from the community. 

> BTW, do you have a timeline for the next major release (so we know when we have to change our software)?

I cannot give you a specific timeline. Generally, each release takes two years. I would say between late 2024 and early 2025.
