### ISSUE TITLE
Some typos in cuSPARSE samples CMakeLists.txt

### ISSUE THREAD

**Issue by Forsworns** [NVIDIA/CUDALibrarySamples#155]
The `cuSPARSE/gpsvInterleavedBatch/CMakeLists.txt` and `cuSPARSE/coosort/CMakeLists.txt` configure the target to *.cu, while the source file is in fact `cuSPARSE/gpsvInterleavedBatch/gpsvInterleavedBatch_example.c` and `cuSPARSE/coosort/coosort_example.c`

https://github.com/NVIDIA/CUDALibrarySamples/blob/1ce6f17e8fc2dcdcf8264dd7b246a0b4b9298a97/cuSPARSE/gpsvInterleavedBatch/CMakeLists.txt#L59

https://github.com/NVIDIA/CUDALibrarySamples/blob/1ce6f17e8fc2dcdcf8264dd7b246a0b4b9298a97/cuSPARSE/coosort/CMakeLists.txt#L59

**Comment by fbusato** [comment]
This has been fixed. Please check the last version of the `master` branch
