### ISSUE TITLE
host memory and GPU memory

### ISSUE THREAD

**Issue by pytho12** [NVIDIA/CUDALibrarySamples#157]
The input of the nvJPEG library is in the host memory and the output is in the GPU memory. Can the input be in the GPU memory and the output be in the GPU memory?

**Comment by zohebk-nv** [comment]
For decoder, we do have `NVJPEG_BACKEND_GPU_HYBRID_DEVICE ` and `NVJPEG_BACKEND_GPU_HYBRID_DEVICE ` backends that accept input bitstreams on device memory. See this [link](https://docs.nvidia.com/cuda/nvjpeg/index.html#nvjpeg-backend) for details. There are certain limitations
1. These backends work only with  `​nvjpegDecodeBatched()` API
2. You will need to know in advance that the jpeg files in question are supported by nvjpeg. If not you will have to copy the bitstream to host and use  `nvjpegDecodeBatchedSupported()` API to determine whether your image is supported by nvjpeg.

**Comment by pytho12** [comment]
Doesn’t encoding support exist?

**Comment by zohebk-nv** [comment]
There is encoding support as well.  The encode APIs([nvjpegEncodeYUV](https://docs.nvidia.com/cuda/nvjpeg/index.html#id1) and [nvjpegEncodeImage](https://docs.nvidia.com/cuda/nvjpeg/index.html#id2)) accept input on device memory. It is possible to retrieve the compressed bitstream on either on device using - [nvjpegEncodeRetrieveBitstreamDevice](https://docs.nvidia.com/cuda/nvjpeg/index.html#nvjpegencoderetrievebitstreamdevice) or on host using 
[nvjpegEncodeRetrieveBitstream](https://docs.nvidia.com/cuda/nvjpeg/index.html#nvjpegencoderetrievebitstream)

**Comment by zohebk-nv** [comment]
closing. Feel free to reopen if you have additional questions
