### ISSUE TITLE
nvJPEG library: rgb32 encoding to JPG

### ISSUE THREAD

**Issue by pytho12** [NVIDIA/CUDALibrarySamples#158]
I have now mastered the method of encoding rgb24 to jpg, but I still don’t know the method of encoding rgb32 to jpg. Can you share it?

**Comment by zohebk-nv** [comment]
rgb32(assuming rgb + 8 bit alpha) support is not well defined in the JPEG standard. You will need to convert rgb32 to rgb 24 before calling nvjpeg encoder.
