### ISSUE TITLE
Information about availability in Docker containers 

### ISSUE THREAD

**Issue by ayushchatur** [NVIDIA/CUDALibrarySamples#159]
Hello, I wonder whether these libraries are part of deep learning containers ?  Specifically, Pytorch containers  https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-07.html

Or whether these are part of CUDA runtime ?

**Comment by JanuszL** [comment]
Hi @ayushchatur,

Most of the libraries are part of the CUDA toolkit and in effect, they are included in the mentioned container. Some of them are not like nvTIFF.
Do you have any specific library in mind?@ptrendx - for now you need to rely on [the experimental video reader](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.readers.video.html) to handle these.

**Comment by ayushchatur** [comment]
@JanuszL  My ultimate goal is to leverage **cusparselt** with PyTorch cpp extension to leverage 2:4 sparsity and on tensor cores . Hence I am going a bit methodically. Here is what i plan to do: 
1. Try and test (compile and test) cusparselt cuda kernel with the given examples in your documentation. 
2. Benchmark with and without sparsity on CUDA and tensor core respectively. 
3. Do point 3. for different precision types
4. Call this cuda kernel with PyTorch
