### ISSUE TITLE
Fail to compile cusparse example dense2sparse

### ISSUE THREAD

**Issue by linbinskn** [NVIDIA/CUDALibrarySamples#16]
Hello, I met some question when tested the example. When compile the dense2sparse example, the following error would emerge:
`dense2sparse_example.c:121:41: error: ‘CUSPARSE_DENSETOSPARSE_ALG_DEFAULT’ undeclared (first use in this function)
                                         CUSPARSE_DENSETOSPARSE_ALG_DEFAULT`
**My environment set up is**:
os : ubuntu 16.04
GPU: GTX2080
CUDA version/driver : 11.1 / 455.23.05
Can you help me analyze why this error caused? Thank you very much.

**Comment by fbusato** [comment]
`CUSPARSE_DENSETOSPARSE_ALG_DEFAULT` enum and `cusparseDenseToSparse` routine are only available in CUDA 11.1.1 (CUDA 11.1 Update 1) or above, see the [release notes](https://docs.nvidia.com/cuda/archive/11.1.1/cuda-toolkit-release-notes/index.html)

**Comment by linbinskn** [comment]
Have solved such problem. Thank you!
