### ISSUE TITLE
[cuSPARSELT] Performance differences between cusparseLtSpMMACompress and cusparseLtSpMMACompress2?

### ISSUE THREAD

**Issue by cj831880** [NVIDIA/CUDALibrarySamples#165]
Are there are any performance differences between `cusparseLtSpMMACompress` and `cusparseLtSpMMACompress2` or any other reason why using one over the other?

**Comment by fbusato** [comment]
no, both functions call the same internal kernel.  The only difference is that `cusparseLtSpMMACompress2` is decoupled from the Plan
