### ISSUE TITLE
 Batched Sparse Matrix -  Batched Sparse Matrix multiplication

### ISSUE THREAD

**Issue by iminfine** [NVIDIA/CUDALibrarySamples#168]
Can make spGEMM support also 3D tensor (might think as batched):
suppose one sparse matrix has dimensions (B, M, N), the other has dimensions (B, N, F)
and the multiplication result has dimensions (B,M,F)?

**Comment by fbusato** [comment]
Hi @iminfine, your idea is good. Unfortunately, we have limited bandwidth, and we need a strong use case for this feature. SpGEMM is a complex routine and adding batched computation, with potentially different sparsity patterns, would require significant effort on our side
