### ISSUE TITLE
cuSparseLt Demo occur Error：CUSPARSE API failed at line 196 with error: initialization error (1)

### ISSUE THREAD

**Issue by matrix97317** [NVIDIA/CUDALibrarySamples#169]
Code: https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSELt/matmul_advanced
![image](https://github.com/NVIDIA/CUDALibrarySamples/assets/76250408/386fe1df-4b14-4522-9c3f-735f1b3f42ae)

**Comment by matrix97317** [comment]
I have solved the above problem. Main Method: Select cuSparseLt Version. But I find a new  problem for cuSparseLt 0.4.0
![image](https://github.com/NVIDIA/CUDALibrarySamples/assets/76250408/416622f0-abc0-4357-95a4-cf808c434285)

**Comment by fbusato** [comment]
Hi @matrix97317, we need more context to understand the problem. First, my suggestion is to use the latest version of the library. Then, can you please provide the GPU model that you are using? are you using the example without modifications?

**Comment by matrix97317** [comment]
GPU: gtx3080ti 
GPU Driver: 520.61.05
CUDA: 11.8
CusparseLt: 0.4.0
Code:  https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSELt/matmul_advanced

I don't change any example code.

**Comment by fbusato** [comment]
Please try with the [latest version 0.5.2](https://developer.nvidia.com/cusparselt-downloads).
`gtx3080ti`  is out of scope for our testing. Our targets are datacenter GPUs, not desktop ones. Anyway, we will run a quick check on this GPU model.

**Comment by matrix97317** [comment]
Thanks for your reply. For the latest version 0.5.2, it's correct.
