### ISSUE TITLE
Incorrect matrix product in example for cusparseSpSM CSR

### ISSUE THREAD

**Issue by BenVanDerMeer** [NVIDIA/CUDALibrarySamples#175]
In the examples for cusparseSpSM CSR (https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSE/spsm_csr). The given matrix product is incorrect, and the A matrix isn't even triangular? Not sure what's happening here.

**Comment by malmasri7** [comment]
Hi @BenVanDerMeer,
The formula should be `op(A) * X = alpha * op(Y)`, where **X is the output** and **Y is the input (RHS)**.  [To fix soon]
SpSM and SpSV take a square sparse matrix and use [cusparseSpMatSetAttribute()](https://docs.nvidia.com/cuda/cusparse/index.html#cusparsespmatsetattribute) to specify the fill mode: lower/upper and diagonal type: unit/non-unit. Please let me know if you have more questions.
