### ISSUE TITLE
cusparseConstrainedGeMM is not working with data type CUDA_R_16F

### ISSUE THREAD

**Issue by apuaaChen** [NVIDIA/CUDALibrarySamples#18]
Hi! I'm trying to use the cusparseSpGEMM. I got the correct results when the data type is CUDA_R_32F and CUDA_R_64F. However, after changing to CUDA_R_16F, the program reports an error as follows
```
On entry to cusparseConstrainedGeMM_bufferSize(): type of matA/matB (CUDA_R_16F), matC (CUDA_R_16F), compute (-1185136882) is not supported
```
I attached my code below, and I'm using the docker image `11.2.0-devel-ubuntu18.04` on V100 GPU. The driver version is 418.126.02 and the CUDA Verison is 11.2.
![image](https://user-images.githubusercontent.com/34239936/106085942-02224400-60d6-11eb-9c27-f29e339ebfbe.png)

In the [document](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-cgemm), it says types including CUDA_R_16F, CUDA_R_32F, CUDA_R_64F are supported.

[code.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/5884559/code.zip)

**Comment by fbusato** [comment]
The documentation of `cusparseConstrainedGeMM` is wrong. `CUDA_R_16F` and `CUDA_C_16F` are not supported. Do you have a specific application for using `CUDA_R_16F` with `cusparseConstrainedGeMM`?

**Comment by apuaaChen** [comment]
> The documentation of `cusparseConstrainedGeMM` is wrong. `CUDA_R_16F` and `CUDA_C_16F` are not supported. Do you have a specific application for using `CUDA_R_16F` with `cusparseConstrainedGeMM`?

Thank you for your reply! I just want to include it as a baseline of my research paper, as I thought it supports FP16 after reading the documentation. It's fine if CUDA_R_16F is not supported.
