### ISSUE TITLE
cuSparseLT API makes it difficult to verify 2:4 format of the weight at model load time

### ISSUE THREAD

**Issue by yuslepukhin** [NVIDIA/CUDALibrarySamples#19]
When I load the model, I would like to verify 2:4 format for the constant sparse weights that come with the model. 

However, `cusparseLtSpMMAPruneCheck` requires arguments that are only available at runtime. 

For example, to create `cusparseLtMatmulDescriptor_t`, we need to create descriptors for B and C.  The exact dimensions for B are not known until the runtime and the same is true for C. 

Can we not verify an chunk of data for 2:4 without knowing the variable dimension for B?

Sorry for the confusion, we actually swap A and B during the computations.

**Comment by fbusato** [comment]
That's a good point, but there is a reason behind that. The 2:4 sparsity pattern depends on the layout of A and `opA`. Without this information it is not possible to check the correctness. My suggestion is to create a fake B, C, and `cusparseLtMatmulDescriptor_t` and then call `cusparseLtSpMMAPruneCheck `.

**Comment by yuslepukhin** [comment]
@fbusato I will follow you suggestion and then also compress the 2:4 matrix so it is available at runtime. Thanks!

**Comment by yuslepukhin** [comment]
I guess, a similar complaint. To compress sparse matrix and copy it to GPU I need the whole shebang setup which effectively prevents me to prepare (copy) things in advance. I feel this is not even consistent with the library own strategy of prepare once, execute many times.

**Comment by fbusato** [comment]
> So the question is, is it even worth compressing in advance and copying?

In general copying and compressing should take a small percentage of the actual matmul (<5%)

> Can I use this compressed copy based on the fake descriptors?

yes, you can keep the device compressed matrix and pass the pointer to `cusparseLtMatmul`. The layout and the operation `opA` must be the same

**Comment by yuslepukhin** [comment]
Thanks for the suggestion. It will, of course, work, but it will consume memory and whatever CPU it takes which is a defeat for sparse structures, especially in view of latest GPT and alike models.

**Comment by federico-busato** [comment]
yes, I agree. Do you have suggestions in this direction?

**Comment by fbusato** [comment]
I agree. Do you have suggestions in this direction?

**Comment by yuslepukhin** [comment]
Well, ideally, I would love to have a way to preprocess initializer data into the most efficient way depending on the library I intend to use depending on the HW availability and user preferences. For cuSparseLT it would be verify, copy to GPU, compress and then throw away in host memory copy. For cuSparse I would convert it to the desired format and then also copy to GPU and then repeatedly use it to compute Gemm. And it would be nice to have it independent of the dense matrix dimensions.
While the fixed dimensions can be obtained after we run shape inferences, I would get stuck when I get to infer models with symbolic/dynamic shapes.

**Comment by fbusato** [comment]
I agree that the pruning check should be independent of the matrix dimensions (but `opA` is needed).
While leaving to cuSPARSELt the responsibility of verifying, copying, compressing, and host memory management is not possible. We need to give the user the maximum flexibility, e.g. the data could be already in the device memory, or the user doesn't need to check the pruning, asynchronous computation, etc.

**Comment by yuslepukhin** [comment]
> I agree that the pruning check should be independent of the matrix dimensions (but `opA` is needed).

This sounds good.

**Comment by yuslepukhin** [comment]
Question. Can I swap arguments in  multiplication and utilize implicit transpose? Essentially, instead of AB=C, do B(T) * A (T) = C(T) but the transpose would be implicit since I would feed data in raw major format but say it is column major.

This trick works in cuBlas dense calculations. Would this work with a compressed sparse matrix?

**Comment by fbusato** [comment]
this feature is planned for the next release but it is not yet available. The sparse matrix must be the first argument for now

**Comment by yuslepukhin** [comment]
> this feature is planned for the next release but it is not yet available. The sparse matrix must be the first argument for now

Is it the same for cuSparse library? The current  [online docs say](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-enum-layout) that only Column Major order is supported, so for Row Major format, we would have to swap arguments anyway, otherwise can't use it.

**Comment by fbusato** [comment]
The documentation is wrong. I will correct it for the next release. cuSPARSE supports column-major and row-major for SpMM [https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spmm](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spmm). 
Note that also cuSPARSELt supports both layouts [https://docs.nvidia.com/cuda/cusparselt/functions.html#matmul-functions](https://docs.nvidia.com/cuda/cusparselt/functions.html#matmul-functions)

**Comment by fbusato** [comment]
thanks again for the feedback. We will try to apply your suggestions soon.
