### ISSUE TITLE
Possible crash issue related to cusparseSparseToDense routines

### ISSUE THREAD

**Issue by UsherWang** [NVIDIA/CUDALibrarySamples#20]
Find a possible crash situation for cusparseSparseToDense with valid input data. The sample code, which is basically the same as example provided with small change related to initialization of sparse matrix from files attached, and the data files associated to sparse matrix, are all attached. Tested under both CUSPARSE_ORDER_COL and CUSPARSE_ORDER_ROW (controlled by macro dense_mat_in_col_major) cases with same error saying:

CUDA API failed at line 204 with error: an illegal memory access was encountered (700)

I am using visual studio 2017 SDK version 10.0.15063.0 with CUDA 11.2. Hardware is 1080ti & 2080ti and intel i7-8700k. Tested on both 1080ti and 2080ti with the same error report.

[Code_Data.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/5899142/Code_Data.zip)

**Comment by fbusato** [comment]
Thanks for reporting the problem. I'm able to reproduce the error on my side. The fix will be present in the next release (not in the upcoming release)
