### ISSUE TITLE
cublasMpGemm treats CUBLAS_OP_T as if it is CUBLAS_OP_C

### ISSUE THREAD

**Issue by dmt4** [NVIDIA/CUDALibrarySamples#204]
Observed in nvhpc v24.5 and also v24.7 unfortunately.

Previous versions seem correct.

**Comment by almogsegal** [comment]
Hi @dmt4,

Thanks for reporting this. It will be fixed in the next release. 

Best,
Almog

**Comment by dmt4** [comment]
Hi Almog, looks like cublasmp v0.3.0 didn't make it in nvhpc v24.11, it still has v0.2.1. Are there blocking issues or some incompatibility?

**Comment by almogsegal** [comment]
Hi @dmt4, [cuBLASMp 0.3.1](https://developer.nvidia.com/cublasmp-downloads), which includes that fix, is available on DevZone. It will be included in HPC-SDK 25.1.
