### ISSUE TITLE
cuBLASLt gemm input int8 output bf16,got error

### ISSUE THREAD

**Issue by zhink** [NVIDIA/CUDALibrarySamples#207]
L20 is work;but A30 crash
code is   
    void const* A = params.weight;
    void const* B = params.act;
    void* D = params.output;

    int m = params.m, n = params.n, k = params.k;
    float h_alpha = params.alpha;
    void* workspace = nullptr;
    size_t workspaceSize = 32 * 1024 * 1024; // 32MB for Hopper
    cudaMalloc(&workspace, workspaceSize);

    cudaStream_t stream;
    cudaStreamCreate(&stream);
    cudaEvent_t begin, end;
    cudaEventCreate(&begin);
    cudaEventCreate(&end);
    cublasLtHandle_t ltHandle;

    checkCublasStatus(cublasLtCreate(&ltHandle));
    cublasLtMatmulDesc_t operationDesc = NULL;
    cublasLtMatrixLayout_t Adesc = NULL, Bdesc = NULL, Cdesc = NULL, Ddesc = NULL;
    cublasLtMatmulPreference_t preference = NULL;

    // only support TN for FP8
    cublasOperation_t transa = CUBLAS_OP_T;
    cublasOperation_t transb = CUBLAS_OP_N;
    float h_beta = 0.0; // Can be non-zero starting from 12.0

    int returnedResults = 0;
    cublasLtMatmulHeuristicResult_t heuristicResult = {};

    // create operation desciriptor; see cublasLtMatmulDescAttributes_t for details about defaults; here we just need to
    // set the transforms for A and B
    checkCublasStatus(cublasLtMatmulDescCreate(&operationDesc, CUBLAS_COMPUTE_32F, CUDA_R_32F));
    checkCublasStatus(
        cublasLtMatmulDescSetAttribute(operationDesc, CUBLASLT_MATMUL_DESC_TRANSA, &transa, sizeof(transa)));
    checkCublasStatus(
        cublasLtMatmulDescSetAttribute(operationDesc, CUBLASLT_MATMUL_DESC_TRANSB, &transb, sizeof(transb)));
    // create matrix descriptors, we are good with the details here so no need to set any extra attributes
    // table of supported type combinations can be found in the documentation:
    // https://docs.nvidia.com/cuda/cublas/index.html#cublasltmatmul
    checkCublasStatus(cublasLtMatrixLayoutCreate(&Adesc, CUDA_R_8I, k, n, k));
    checkCublasStatus(cublasLtMatrixLayoutCreate(&Bdesc, CUDA_R_8I, k, m, k));
    checkCublasStatus(cublasLtMatrixLayoutCreate(&Cdesc, CUDA_R_16BF, n, m, n));
    checkCublasStatus(cublasLtMatrixLayoutCreate(&Ddesc, CUDA_R_16BF, n, m, n));
    // create preference handle; here we could use extra attributes to disable tensor ops or to make sure algo selected
    // will work with badly aligned A, B, C; here for simplicity we just assume A,B,C are always well aligned (e.g.
    // directly come from cudaMalloc)
    checkCublasStatus(cublasLtMatmulPreferenceCreate(&preference));
    checkCublasStatus(cublasLtMatmulPreferenceSetAttribute(
        preference, CUBLASLT_MATMUL_PREF_MAX_WORKSPACE_BYTES, &workspaceSize, sizeof(workspaceSize)));
    checkCublasStatus(cublasLtMatmulAlgoGetHeuristic(
        ltHandle, operationDesc, Adesc, Bdesc, Cdesc, Ddesc, preference, 1, &heuristicResult, &returnedResults));

mnk (1, 4096, 4096), output 13__nv_bfloat16

[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtCreate] lightHandle=0X7FFC9529E758
[2024-08-12 02:14:03][cublasLt][78848][Info][cublasLtCreate] cuBLASLt v12.0 device #0: multiProcessorCount=56 maxSharedMemPerBlock=49152 maxSharedMemoryPerBlockOptin=166912
1[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtMatmulDescCreate] matmulDesc=0X7FFC9529E750 computeType=COMPUTE_32F scaleType=0
[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtMatmulDescSetAttribute] matmulDesc=0X2672810 attr=MATMUL_DESC_TRANSA buf=0X7FFC9529E724 sizeInBytes=4
[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtMatmulDescSetAttribute] matmulDesc=0X2672810 attr=MATMUL_DESC_TRANSB buf=0X7FFC9529E720 sizeInBytes=4
1[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtMatrixLayoutCreate] matLayout=0X7FFC9529E748 type=R_8I rows=4096 cols=4096 ld=4096
[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtMatrixLayoutCreate] matLayout=0X7FFC9529E740 type=R_8I rows=4096 cols=1 ld=4096
[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtMatrixLayoutCreate] matLayout=0X7FFC9529E738 type=R_16BF rows=4096 cols=1 ld=4096
[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtMatrixLayoutCreate] matLayout=0X7FFC9529E730 type=R_16BF rows=4096 cols=1 ld=4096
1[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtMatmulPreferenceCreate] matmulPref=0X7FFC9529E728
[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtMatmulPreferenceSetAttribute] pref=0X3591460 attr=MATMUL_PREF_MAX_WORKSPACE_BYTES buf=0X7FFC9529E778 sizeInBytes=8
0[2024-08-12 02:14:03][cublasLt][78848][Api][cublasLtMatmulAlgoGetHeuristic] Adesc=[type=R_8I rows=4096 cols=4096 ld=4096] Bdesc=[type=R_8I rows=4096 cols=1 ld=4096] Cdesc=[type=R_16BF rows=4096 cols=1 ld=4096] Ddesc=[type=R_16BF rows=4096 cols=1 ld=4096] preference=[maxWavesCount=0.0 maxWorkspaceSizeinBytes=33554432] computeDesc=[computeType=COMPUTE_32F scaleType=R_32F transa=OP_T]
cuBLAS API failed with status 15
terminate called after throwing an instance of 'std::logic_error'
  what():  cuBLAS API failed
Aborted (core dumped)

**Comment by rsdubtso** [comment]
Hello @zhink. This type combination is not supported by cuBLAS. Please check supported combinations [here](https://docs.nvidia.com/cuda/cublas/#id103).
