### ISSUE TITLE
Possible bug related to cusparseDenseToSparse routines

### ISSUE THREAD

**Issue by UsherWang** [NVIDIA/CUDALibrarySamples#21]
Find a possible bug for cusparseDenseToSparse routines with valid input data. The sample code, which is basically the same as example provided with small change related to initialization of dense matrix from files attached, and the data files associated to dense matrix, are all attached. The code attached tries to convert a dense matrix into CSR format. However the column indices for each row is not in ascending order. Would like to make sure if such behavior is as expected. 

I am using visual studio 2017 SDK version 10.0.15063.0 with CUDA 11.2. Hardware is 1080ti & 2080ti and intel i7-8700k. Tested on both 1080ti and 2080ti with the same behavior.

[Code_Data.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/5899159/Code_Data.zip)

**Comment by fbusato** [comment]
yes, this is the expected behavior. Even if CSR column indices are not sorted, it is still a valid CSR format
