### ISSUE TITLE
Which Visual Studio 2022 BuildTools MSVC is the best version for Cuda 11.8 and Cuda 12.4 and so

### ISSUE THREAD

**Issue by FurkanGozukara** [NVIDIA/CUDALibrarySamples#217]
I keep having issues when compiling apps that requires CUDA and C++ tools on windows

I would like to learn best version for CUDA 11.8 and CUDA 12.4

There are so many versions listed here and not all of them working

https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history

For example recently I am compiling XPose and it is so sensitive to the C++ versions

Which version from above list do you suggest?

The list starts from 17.0 to 17.10

Can we say that LTSC 17.10 is better than LTSC 17.4

I really need help with this

**Comment by baliika** [comment]
Hi @FurkanGozukara ,
Thanks for your question.
Generally newer versions of the MSVC compiler provide fixes for previously spotted issues, quite likely they add optimizations (speed, space, memory-efficiency, etc.), and compliance for newer C++ standards, potentially newer architectures (e.g., ARM).

For CUDA Toolkit 11.8, I can recommend LTSC 17.4.x (where x is the latest patch version), as this MSVC compiler is supported by the nvcc shipped in this version of CTK (to the best of my knowledge, this is the latest one supported), and one does not need to add the `--allow-unsupported-compiler` flag - adding some confidence, that the resulting binary will be void of compilation-related issues.

For CUDA Toolkit 12.4, I'd recommend pulling the latest one (or close to the latest one, e.g., 17.10.x). I tried it with the BuildTools version 17.11.5, and it was working flawlessly.

Extra tip: MSVC has something called build customizations. The CTK installers populate these build customizations as they detect the installed MSVC variants on the system. However, if one installs the MSVC variants only after the CTK variants, the build customizations might need to be populated manually. Therefore, I recommend installing the MSVC compilers on the system first, then install the used CUDA Toolkits.

**Comment by FurkanGozukara** [comment]
@baliika Thanks

I went with 17.8 I think supports both

**Comment by baliika** [comment]
If LTSC 17.8 works for you, and this solved your problems, could you mark this issue Closed?

However, if you still have questions, we are here to help. Thanks!
