### ISSUE TITLE
Possible confusing routine definition in cuSparse doc in CUDA 11.2

### ISSUE THREAD

**Issue by UsherWang** [NVIDIA/CUDALibrarySamples#22]
Hi there, 

Just find a confusing routine definition in section 14.6.11 of cuSparse library doc: 

cusparseStatus_t CUSPARSEAPI
cusparseSpGEMM_copy(cusparseHandle_t      handle,
                    cusparseOperation_t   opA,
                    cusparseOperation_t   opB,
                    const void*           alpha,
                    cusparseSpMatDescr_t  matA,
                    cusparseSpMatDescr_t  matB,
                    const void*           beta,
                    cusparseSpMatDescr_t  matC,
                    cudaDataType          computeType,
                    cusparseSpGEMMAlg_t   alg,
                    cusparseSpGEMMDescr_t spgemmDescr,
                    void*                 externalBuffer2);

In example provided and my own tests, function cusparseSpGEMM_copy only works without taking the last input variable 'void* externalBuffer2'. Just FYI.

**Comment by fbusato** [comment]
Thanks for reporting the issue. The documentation is wrong. It will be updated in the next release
