### ISSUE TITLE
cusparseLt 0.6.1 Error on H20: architecture mismatch

### ISSUE THREAD

**Issue by x574chen** [NVIDIA/CUDALibrarySamples#223]
### Configurations
cuSPARSELt version: 0.6.1
Hardware: H20 8x
cuda version: 12.4
Driver: 550.90.07

### Problem
When integrating cuSPARSE into our inference engine, some H20 tests reported errors in the cusparseLtInit API:
`CUSPARSELT API failed at line 78 with error: architecture mismatch (4)`

According to the debug logs, the error seems to be caused by lack of support for SM90:
`[2024-10-10 19:53:11][CUSPARSELT][46965][Trace][cusparseLtInit] cudaGetDeviceProperties(0)`
`[2024-10-10 19:53:11][CUSPARSELT][46965][Error][cusparseLtInit] cusparseLt currently supports only SM80, SM86, SM89 (current: SM90)
`

However, according to the cuSPARSELt [documentation](https://docs.nvidia.com/cuda/cusparselt/release_notes.html#cusparselt-v0-6-0), support for the Hopper architecture was introduced in version 0.6.0. Is it possible that the "architecture mismatch" error is caused by other conditions?

**Comment by j4yan** [comment]
@x574chen This looks weird since 0.6.1 definitely supports SM90. Are you sure you are using 0.6.1? Could you double check the version, for example by `cusparseLtGetVersion()`?

**Comment by sixt99** [comment]
Same issue here
