### ISSUE TITLE
[QST] cublasDx: cuda::std::byte instead of char for shared memory?

### ISSUE THREAD

**Issue by osayamenja** [NVIDIA/CUDALibrarySamples#227]
Hey!

This may be the wrong place for this, but MathDx does not have a GitHub-like forum, so I decided to relay it here.

`slice_shared_memory` accepts a char* pointer to the shared memory workspace; is there a reason against using `cuda::std::byte` or unsigned char ([underlying type of std::byte](https://en.cppreference.com/w/cpp/types/byte)) instead? 

### References
[Stackoverflow on byte*](https://stackoverflow.com/questions/45435875/with-stdbyte-standardized-when-do-we-use-a-void-and-when-a-byte)

### Edits
Oops, I completely overlooked `struct smem_alignment<...>` which casts the shared memory pointer to value types of the corresponding matrices. Due to this, I will remove the code example as it is misleading.

**Comment by jszuppe** [comment]
>  is there a reason against using `cuda::std::byte` or unsigned char ([underlying type of std::byte](https://en.cppreference.com/w/cpp/types/byte)) instead?

It's a good point. Thanks! We'll consider using `unsigned char` instead of `char`, and adding API which accepts `cuda::std::byte`.

**Comment by osayamenja** [comment]
Thank you @jszuppe will close this.
