### ISSUE TITLE
Possible bug related to cusparseCnnz_compress 

### ISSUE THREAD

**Issue by UsherWang** [NVIDIA/CUDALibrarySamples#23]
Find a possible bug associated to cusparseCnnz_compress with valid input data. The returned non-zero elements number and non-zero elements per row are incorrect for specific input. The sample code and the data files associated to input csr sparse matrix, are attached. 

I am using visual studio 2017 SDK version 10.0.15063.0 with CUDA 11.2. Hardware are 1080ti & 2080ti and intel i7-8700k. Tested on both 1080ti and 2080ti with different behavior. Inside attached package, there are two subfolders called 'data_for_1080ti' and 'data_for_2080ti', indicating data that triggers wrong output for each hardware from my side. The correct & wrong output of total non-zero number for 'data_for_1080ti' on 1080ti is:
nnz_cpu = 1282036 (correct)
nnz_gpu = 1281069 (wrong)
The output for 'data_for_2080ti' on 2080ti is:
nnz_cpu = 1590140 (correct)
nnz_gpu = 1589628 (wrong)
[code_data.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/5938337/code_data.zip)

**Comment by federico-busato** [comment]
Hi, thanks for reporting the issue. Can you please open an official bug? [https://developer.nvidia.com/nvidia_bug/add](https://developer.nvidia.com/nvidia_bug/add)

**Comment by UsherWang** [comment]
sure, no problem. Thank you for your info.

**Comment by fbusato** [comment]
we got the notification of bug by using the standard procedure. Let's trace the bug there
