### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [NVIDIA/CUDALibrarySamples#238]
I suggest adding topics such as `cuda`, `blas`, `linear-algebra`, `fft`, `gpu`, `cublas` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by JanuszL** [comment]
Hi @Beliavsky,

Thank you for reaching out and your suggestion.
Applied.
