### ISSUE TITLE
cuSparse BlockedEll sparse format documentation is incomplete online

### ISSUE THREAD

**Issue by yuslepukhin** [NVIDIA/CUDALibrarySamples#24]
I am looking at [cusparseCreateBlockedEll](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-spmat-create-blockedell) and it looks like the library does not offer any conversion helpers in the likes of Csr/Coo formats. Am I missing something?

Also, I am looking at the BlockedEll format description and it does not mention what should be the value for a missing block index. For example, if the last row of blocks has only one non-zero block, what should be the value of the missing block column index? Would it be -1 or something else?

![image](https://user-images.githubusercontent.com/11303988/108437994-38e60880-7203-11eb-8027-48ba208c4d03.png)

Another issue is that `cusparseCooSetPointers` does not appear to have online documentation but is present in the header file.

**Comment by fbusato** [comment]
CUDA 11.2.1 is the first release that provides the blocked-ELL format. The priority for this format is performing tensor core-accelerated matrix multiplication. We are already working on the conversion routine from dense to blocked-ELL and it will be provided soon.
About the missing block question, the format requires that all rows have the same number of blocks. If you want to represent an empty block, you can always fill the block with zero values. Anyway, it is a nice suggestion to use a special index, e.g. -1 to represent this situation. We will take into account the proposal.
Finally, about `cusparseCooSetPointers`, you are right. It is missing from the documentation. We will fix it. In the meanwhile, you can refer to https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-spmat-create-csr as the behavior is almost identical

**Comment by yuslepukhin** [comment]
@fbusato Thank you for the comprehensive response. One thing is missing though.

> About the missing block question, the format requires that all rows have the same number of blocks. If you want to represent an empty block, you can always fill the block with zero values. Anyway, it is a nice suggestion to use a special index, e.g. -1 to represent this situation. We will take into account the proposal.

Say, in the above picture, the last row has only index 2 present. I can certainly append a zeroed block (although I wrote code to detect and git rid of them), but what should be its index? Anything beyond 2 is out of bounds.

**Comment by fbusato** [comment]
Maybe I'm understanding the issue. The figure represents the dense matrix before the conversion to the blocked-ell format. In the blocked-ell format all values are contiguous (following the memory location in the figure) and there is no padding. If you want to represent a zero block, you have to keep the same indices and put the value in 39,40,41; 45,46,67; 51,52,53 to zero

**Comment by yuslepukhin** [comment]
@fbusato Here is an illustration. Typically, in Ell the non-zero col indices are shifted to the left and padded on the right for the missing blocks. Now I need to add a fake block of zeros. Imaging the following picture. In this case, the only on-zero block on the last row has index 2. I can not append, since it is the last block. So I will have to make a decision which indices are free to use them for fake blocks. In the picture below I will have to insert a fake block before 2 in order to use indecies 0 or 1.

![EllIssue](https://user-images.githubusercontent.com/11303988/108547175-025dcb80-729f-11eb-8d1f-78e1c8d7bade.jpg)

The picture becomes more complicated for other cases. Say we have not 3 but 4 block columns and indecies 1 and 3 are valid non-zero blocks. I will have to detect first that 0 and 2 can be re-used for fake blocks and insert them as appropriate.

**Comment by yuslepukhin** [comment]
I tried to test the example and I am getting a diagnostic print out:
On entry to cusparseCreateBlockedEll(): ellCols (2) is not a multiple of block size (3)
From the picture above, ellCols can not be possibly a multiple of block size. Is it an implementation bug or a documentation bug?

**Comment by fbusato** [comment]
Maybe I'm not understanding it in the right way but if you want to run the example of the figure `ellCols` should be `6` not `2`

**Comment by yuslepukhin** [comment]
> Maybe I'm not understanding it in the right way but if you want to run the example of the figure `ellCols` should be `6` not `2`

This is helpful. The documentation has to be fixed, IMHO.

Well, the ell index on the picture has 2 columns but, the documentation states:
`Actual number of columns of the Blocked-Ellpack format` which need more clarity.

**Comment by fbusato** [comment]
thanks for the suggestion. We will update the documentation

**Comment by fbusato** [comment]
All issues discussed here are planned and the fixes will be provided in the next CUDA Toolkit version (not in the upcoming one)
