### ISSUE TITLE
Minor issue: LTSgemm m, n, k integer variables

### ISSUE THREAD

**Issue by faruknane** [NVIDIA/CUDALibrarySamples#25]
Hi,
cublaslt sgemm supports int64 vector and matrix sizes. Is it possible to change m, n, k and lda, ldb etc as uint64_t?
https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuBLASLt/LtSgemm/sample_cublasLt_LtSgemm.cu

**Comment by pmajch** [comment]
cublasLt API accepts m, n, k in uint64_t and lda, ldb, ldc in int64_t but in the current release only values fitting in int32_t are accepted (see https://docs.nvidia.com/cuda/cublas/index.html#cublasLtMatrixLayout_t ). Out of range values will cause cublasLt routines to return error codes and error messages (after enabling with CUBLASLT_LOG_LEVEL=1) should explain the problems.
