### ISSUE TITLE
j2k support

### ISSUE THREAD

**Issue by RaananHadar** [NVIDIA/CUDALibrarySamples#27]
Trying to open j2k files from DALI results in an error. I was told  that this should be a nvjpeg2000 issue.

**Comment by maheshkha** [comment]
We have release nvJPEG2000 v0.2.0 that support j2k files. 
Can you try with this release?

**Comment by RaananHadar** [comment]
Thank you. I will ask the DALI authors to enable support to j2k and reopen if there are any issues.
