### ISSUE TITLE
undefined reference to cusparseDenseToSparse_convert (analysis and buffersize as well)

### ISSUE THREAD

**Issue by K-H-Ismail** [NVIDIA/CUDALibrarySamples#31]
Hello,
It seems that reference to cusparseDenseToSparse_buffersize, cusparseDenseToSparse_analysis and cusparseDenseToSparse_convert is undefined during linkage. Could you please help me ?

My  setup is:
os : ubuntu 20.10
GPU: GeForce GTX 1050 Ti
CUDA version/driver : 11.3.58 / 460.56

**Comment by federico-busato** [comment]
Hi, sorry for the delay. I didn't receive the notification. Can you please check `LD_LIBRARY_PATH`? does it point to CUDA toolkit 11.3?

**Comment by K-H-Ismail** [comment]
Hello,
with export PATH=$PATH:/usr/local/cuda-11.3/bin/
and export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.3/lib64/ it worked. Thanks for your help !
