### ISSUE TITLE
SVS tile decoding get "NVJPEG2K_STATUS_JPEG_NOT_SUPPORTED"

### ISSUE THREAD

**Issue by weisystak** [NVIDIA/CUDALibrarySamples#32]
Hi,
I want to decode medical image file (SVS). 
I use this [sample code](https://github.com/NVIDIA/CUDALibrarySamples/tree/master/nvJPEG2000/nvJPEG2000-Decoder-Pipelined) without any modification.
But got `NVJPEG2K_STATUS_JPEG_NOT_SUPPORTED`  from `nvjpeg2kStreamParse`.
Here is my [sample bitstream](https://drive.google.com/file/d/1P7KsDbrl67LPQ341aj_uCFPd9l3zK7DW/view?usp=sharing).
It should be decoded like this: 
![tile](https://user-images.githubusercontent.com/26464585/117103543-1e0c4480-adad-11eb-9ddd-ed52e7ad3cc0.png)
It can be decoded successfully using `openjpeg`.

Will nvjpeg2k support this  JPEG2000 stream in the future?

ENV:
Ubuntu 20.04.2 LTS
A100-PCIE-40GB
CUDA Version: 11.2   
Driver Version: 460.73.01   
nvJPEG2000 0.2.0.22

Thanks!

**Comment by maheshkha** [comment]
Hi,

SVS file format for JPEG2000 comes with two compression type 33003 or 33005
For 33003: YCbCr format, possibly with a chroma sub-sampling of 4:2:2.
For 33005: RGB format

Current **nvJPEG2000**  version 0.2.0 do not subsampling.  
We are going to add the sub-sampling (_4:2:0, 4:2:2_) support in upcoming release.

I've decoded the sample image on our upcoming release branch and output results shown below:
![tile](https://user-images.githubusercontent.com/5110350/117221085-6cc1da80-adbd-11eb-9c64-f73c5700285d.jpg)

Will update you once new release is published.

Thanks

**Comment by maheshkha** [comment]
Please use latest release nvJPEG2K 0.3.0 - address this issue.
