### ISSUE TITLE
failed to compile Block-SpMM examples.

### ISSUE THREAD

**Issue by Young768** [NVIDIA/CUDALibrarySamples#33]
Hi folks, I tried to compile Block-SpMM example, but met these errors. Any suggestion to fix it?

`nvcc -I/usr/bin/../include spmm_blockedell_example.cpp -o spmm_blockedell_example -lcudart -lcusparse
spmm_blockedell_example.cpp: In function ‘int main()’:
spmm_blockedell_example.cpp:143:21: error: ‘cusparseCreateBlockedEll’ was not declared in this scope
  143 |     CHECK_CUSPARSE( cusparseCreateBlockedEll(
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~
spmm_blockedell_example.cpp:67:32: note: in definition of macro ‘CHECK_CUSPARSE’
   67 |     cusparseStatus_t status = (func);                                          \
      |                                ^~~~
make: *** [Makefile:54: spmm_blockedell_example] Error 1`

**Comment by GiganticRay** [comment]
Hi Mr Young768, I met the same question with you when I test the dense2sparse_blockedell_example provided by nvidia,  could you share how you fixed it pls? THANKS!

**Comment by GiganticRay** [comment]
> 

I found there isn't declare of **cusparseCreateBlockedEll** in the ```cusparse.h```...

**Comment by Young768** [comment]
I met this issue because I cloned an old version. Did you use the latest commit?
