### ISSUE TITLE
cuSparseLt spmma Makefile typo

### ISSUE THREAD

**Issue by caic99** [NVIDIA/CUDALibrarySamples#34]
https://github.com/NVIDIA/CUDALibrarySamples/blob/ad9b714505bb4cd4131d9bc09f97c5ad800c74d9/cuSPARSELt/spmma/Makefile#L50
Maybe here should be `${CUDA_TOOLKIT}`?

**Comment by fbusato** [comment]
thanks for reporting it. I'm fixing it
