### ISSUE TITLE
cuSPARSELt spmma compute capability check

### ISSUE THREAD

**Issue by shuo-ouyang** [NVIDIA/CUDALibrarySamples#35]
[cuSPARSELt v0.1.0](https://docs.nvidia.com/cuda/cusparselt/release_notes.html#cusparselt-v0-1-0) intorduced SM 8.6 compatibility, maybe we should modify the condition here?
https://github.com/NVIDIA/CUDALibrarySamples/blob/ad9b714505bb4cd4131d9bc09f97c5ad800c74d9/cuSPARSELt/spmma/spmma_example.cpp#L82

**Comment by fbusato** [comment]
thanks for reporting it. I'm fixing it
