### ISSUE TITLE
cuSparseLt Destroy Question

### ISSUE THREAD

**Issue by caic99** [NVIDIA/CUDALibrarySamples#36]
https://github.com/NVIDIA/CUDALibrarySamples/blob/ad9b714505bb4cd4131d9bc09f97c5ad800c74d9/cuSPARSELt/spmma/spmma_example.cpp#L214
cusparseLt destroys handle using its address. Why this behavior differs from cuSparse (see below), cuBlas i.e. not using address but directly pass the handle? 
https://github.com/NVIDIA/CUDALibrarySamples/blob/ad9b714505bb4cd4131d9bc09f97c5ad800c74d9/cuSPARSE/spgemm/spgemm_example.c#L215

**Comment by fbusato** [comment]
yes, the behavior is correct. cuSPARSE and cuSPARSELt have different ways to manage handle and data types. The main reason is that cuSPARSELt tries to allocate everything on the stack for efficiency, while cuSPARSE uses the heap memory mostly for historical reasons
