### ISSUE TITLE
make error (nvJPEG/nvJPEG-Decoder)

### ISSUE THREAD

**Issue by hacktmz** [NVIDIA/CUDALibrarySamples#37]
env: cuda10.2 ubuntu 18.04

(base) root@xx-11-0:/workspace/CUDALibrarySamples-master/nvJPEG/nvJPEG-Decoder/build# make -B
[ 50%] Building CUDA object CMakeFiles/nvjpegDecoder.dir/nvjpegDecoder.cpp.o
/workspace/CUDALibrarySamples-master/nvJPEG/nvJPEG-Decoder/nvjpegDecoder.cpp(56): error: identifier "nvjpegJpegStreamParseHeader" is undefined

/workspace/CUDALibrarySamples-master/nvJPEG/nvJPEG-Decoder/nvjpegDecoder.cpp(58): error: identifier "nvjpegDecodeBatchedSupported" is undefined

/workspace/CUDALibrarySamples-master/nvJPEG/nvJPEG-Decoder/nvjpegDecoder.cpp(331): error: identifier "NVJPEG_BACKEND_HARDWARE" is undefined

3 errors detected in the compilation of "/tmp/tmpxft_00000f8f_00000000-6_nvjpegDecoder.cpp1.ii".
CMakeFiles/nvjpegDecoder.dir/build.make:81: recipe for target 'CMakeFiles/nvjpegDecoder.dir/nvjpegDecoder.cpp.o' failed
make[2]: *** [CMakeFiles/nvjpegDecoder.dir/nvjpegDecoder.cpp.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/nvjpegDecoder.dir/all' failed
make[1]: *** [CMakeFiles/nvjpegDecoder.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stevechaw** [comment]
how did you solve it ?

**Comment by we0091234** [comment]
I have the same problem，have you solved it?

**Comment by xinmans** [comment]
any update? same error
