### ISSUE TITLE
Using int8 TC in cublasLtMatmul

### ISSUE THREAD

**Issue by haihai-00** [NVIDIA/CUDALibrarySamples#41]
Hi,
I m trying to use IMMA kernel with cublasLtMatmul API, with Atype = Btype = Ctype = Dtype = CUDA_R_8I, and alpha =float, beta=float. Here is my quesion about this API:
1. Is this config correct? I think Dtype should be the same with Ctype.
2. Since Dtype is int8, so there is the great chance that the result element of A*B can be greater than 128 or less than -127. and this API just return result as 128 or -127. It is designed be like this, right?
3. What should I do to avoid the overflow of the result in this case with Atype = Btype = CUDA_R_8I and alpha, beta = float? do you have any suggestion?
Thank you！

**Comment by pmajch** [comment]
Hi haihai-00 I hope you have been able to find the answer for this.. for the sake of completeness of this thread:

> 1. Is this config correct? I think Dtype should be the same with Ctype.
This is correct and Ctype==Dtype in this example, and is the only config cuBLASLt currently supports with int8. Please refer to the support matrix in https://docs.nvidia.com/cuda/cublas/index.html#cublasltmatmul for more options (e.g. some fp8 entries have Dtype!=Ctype)

> 2. Since Dtype is int8, so there is the great chance that the result element of A*B can be greater than 128 or less than -127. and this API just return result as 128 or -127. It is designed be like this, right?
This is specifically why alpha is accepted in float. You need to have some expectation of the range of results you will get out from A*B and use a fractional value of alpha to scale it back into the -127 to 128 range of int8.

> 3. What should I do to avoid the overflow of the result in this case with Atype = Btype = CUDA_R_8I and alpha, beta = float? do you have any suggestion?
Please see above. One approach would be to run similar operation in float first then once you learn the typical range appearing in A*B you pick the alpha scalar.
