### ISSUE TITLE
Confusion about the sddmm example in the cuSparse library

### ISSUE THREAD

**Issue by Liu-xiandong** [NVIDIA/CUDALibrarySamples#42]
Hello, I read the example of sddmm and I feel very confused. 
https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSE/sddmm_csr
There are mainly the following two problems:
1. The dimension of C is m*n. A is a 4*4 matrix, and B is a 4*3 matrix. Why does the C get a 4*4 matrix instead of a 4*3 matrix?
2. I calculated the result of A*B, the result should be [[ 70 80 90]
 [158 184 210]
 [246 288 330]
 [324 381 438]]. I don't know why sddmm will get the result of the example.

**Comment by fbusato** [comment]
Thanks for reporting it. There were several typos in this example. It has been fixed in 24b476a70f4e01cfc5813da1bcaefa7a47255a16
