### ISSUE TITLE
On CUDA11.2 of windows and ARM, related cusparseSDDMM APIs are not found in cusparse.h.

### ISSUE THREAD

**Issue by Liu-xiandong** [NVIDIA/CUDALibrarySamples#45]
On CUDA11.2 of **windows** and **ARM**, cusparseSDDMM, cusparseSDDMM_preprocess, and cusparseSDDMM_bufferSize are not found in cusparse.h. But it can be found in the X86 platform of Linux.

**Comment by fbusato** [comment]
yes, you are right. CUDA 11.2 does not provide SDDMM, while it is part of **CUDA 11.2 Update 1**. SDDMM in not documented in CUDA 11.2 and you should not use it even if you see it in the header of X86 Linux. My suggestion is to move to an updated version of the CUDA toolkit

**Comment by Liu-xiandong** [comment]
> yes, you are right. CUDA 11.2 does not provide SDDMM, while it is part of **CUDA 11.2 Update 1**. SDDMM in not documented in CUDA 11.2 and you should not use it even if you see it in the header of X86 Linux. My suggestion is to move to an updated version of the CUDA toolkit

OK，Thanks
