### ISSUE TITLE
Is this picture wrong?

### ISSUE THREAD

**Issue by xue-fc** [NVIDIA/CUDALibrarySamples#46]
https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuSPARSE/spmm_blockedell/spmm_blockedell.png
I think the matrix A is wrong because A doesn't has 9 there.

**Comment by fbusato** [comment]
thanks for reporting the issue. It has been fixed in 0d0f90d6c4760e594c7a4e1563217e2f1d29af29
