### ISSUE TITLE
nvJPEG-Decoder isn't faster on A100 vs V100

### ISSUE THREAD

**Issue by NicolasHug** [NVIDIA/CUDALibrarySamples#50]
Hi, and thanks for providing these examples which are very useful.

I'm running the nvJPEG-Decoder on a A100 GPU and a V100 GPU, and I'm observing pretty much the same decoding times. A typical run for both A100 and V100 is something like:

```
./nvjpegDecoder -i ../input_images/ -o /tmp -w 100
Total decoding time: 12.2522
Avg decoding time per image: 1.02101
Avg images per sec: 0.979419
Avg decoding time per batch: 1.02101
```

Shouldn't we expect the A100 to be much faster?

Also, when I change `NVJPEG_BACKEND_HARDWARE` to instead use `NVJPEG_BACKEND_DEFAULT`, I'm not seing any performance hit on the A100. Is this expected? Am I doing something wrong?

```
nvcc --version:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

Thanks for your help!

**Comment by maheshkha** [comment]
Hi,

Please try to run with following option

`./nvjpegDecoder -i ../input_images/ -o /tmp -w 10 -t 1024 -b 128 `

1. For V100 - running sample will display this 
`Hardware Decoder not supported. Falling back to default backend`

2. On A100 - the default `NVJPEG_BACKEND_HARDWARE `. You should get higher performance here.
