### ISSUE TITLE
Does cusparse_spmm function support multiplying of multiple sparse matrices and multiple dense matrices

### ISSUE THREAD

**Issue by Liu-xiandong** [NVIDIA/CUDALibrarySamples#51]
In  [this doc](https://docs.nvidia.com/cuda/cusparse/index.html#:~:text=cusparseSpMM()-,with,-CUSPARSE_SPMM_COO_ALG4),  nvidia stated that spmm can support batch sparse matrix and batch dense matrix. 
![image](https://user-images.githubusercontent.com/85323580/146302963-bf14dbc4-b941-44c0-b914-dccb36904967.png)

However, it is stated [here](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuSPARSE/spmm_csr_batched/spmm_csr_batched_example.c#:~:text=Multiple-,sparse,-matrices) that multiple sparse matrices are currently not supported.
![image](https://user-images.githubusercontent.com/85323580/146303007-0e921d7d-4360-4141-8e17-913a7a916cd6.png)

**Comment by fbusato** [comment]
Thanks for reporting the issue. You are right. The documentation and the example have conflicting statements. `cusparseSpMM` supports batched computation but there are several definitions for it. We will fix both documentation and example in CUDA 11.6u1.
