### ISSUE TITLE
Revise the product Ax = y

### ISSUE THREAD

**Issue by JMSBornot** [NVIDIA/CUDALibrarySamples#52]
I think there is an error in the product illustration for the example: isn't it A * y = x instead of A * x = y?

**Comment by JMSBornot** [comment]
I mean in the Readme file here: https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSE/spsv_csr

**Comment by fbusato** [comment]
Thank you for reporting this issue. You are right. It affects not only spsv csr but all triangular solver images.
Now it has been fixed.
