### ISSUE TITLE
About cudnn_samples

### ISSUE THREAD

**Issue by Zong-Ming-Jing** [NVIDIA/CUDALibrarySamples#53]
![cudnn-q0](https://user-images.githubusercontent.com/40746878/147621367-3eb69c2e-40da-4083-88ff-77e040179748.png)

the problem is like the fig.
I can't test my cudnn_sample.
the msg show me that 0 error code.

my system is Ubuntu 16.04
     GPU is 2080 Ti
     CUDA is CUDA 9.0
     cudnn is 7.3.1 ( i had try the 7.4 & 7.0 before,and i meet the same problem. )

Anyone can help me ?

next fig is the msg after i do the command "make clean && make" at  the cudnn_sample file.
![cudnn-q1](https://user-images.githubusercontent.com/40746878/147621832-52600ef0-be95-4b30-8522-baefdeb3750d.png)

**Comment by mnicely** [comment]
I suggest posting cuDNN questions on the [forum](https://forums.developer.nvidia.com/c/ai-data-science/deep-learning/cudnn/90)
