### ISSUE TITLE
Find CUDNN Samples 

### ISSUE THREAD

**Issue by WLSheng** [NVIDIA/CUDALibrarySamples#54]
Dear developer:
 I'm going to do cudnn (v8.2.1) development on windows10 and I'm having some problems, but I can't find the official sample code. I would like to ask if CUDNN sample code will be added to this repository, or where is the official CUDNN sample code?
 Looking forward to your reply

**Comment by mnicely** [comment]
I don't believe cuDNN samples aren't currently available online

**Comment by mnicely** [comment]
I suggest posting cuDNN questions on the [forum](https://forums.developer.nvidia.com/c/ai-data-science/deep-learning/cudnn/90)
