### ISSUE TITLE
Problem with cusparseSpMV for datatype CUDA_C_64F

### ISSUE THREAD

**Issue by PvandenBosch** [NVIDIA/CUDALibrarySamples#56]
Hello,
I'm trying to use routine cusparseSpMV for datatype CUDA_C_64F, called from Fortran. First of all I tried to reproduce the example which is at [https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSE/spmv_csr](url). I can run the example for the datatypes CUDA_R_32F and CUDA_C_32F without any issue and with the correct result. However when I change the particular data array's and the datatype to CUDA_C_64F, I get the message:
Unhandled exception at 0x00007ffe6f5d3a1a in Cusparse_t.exe: 0xC0000005: Access violation reading location 0xffffffffffffffff.

I'm using the CUDA toolkit version 11.5.
Operating system Windows 10
Compiler: Intel Fortran 2013 SP1

The code is given below.

Thanks in advance for any help.
Regards,
Peter

``module InterfaceCUDA
Interface
    ! cudaMalloc
    integer (c_int) function cudaMalloc ( buffer, size ) &
                              bind (C, name="cudaMalloc" ) 
        use iso_c_binding
        implicit none
        type (c_ptr)              :: buffer
        integer (c_int), value :: size
    end function cudaMalloc
                              
    integer (c_int) function cudaMemcpy ( dst, src, count, kind ) &
                              bind (C, name="cudaMemcpy" )
   ! note: cudaMemcpyHostToDevice = 1
   ! note: cudaMemcpyDeviceToHost = 2
   ! note: cudaMemcpyDeviceToDevice = 3
        use iso_c_binding
        type (c_ptr), value :: dst, src
        integer (c_int), value :: count, kind
    end function cudaMemcpy

    integer (c_int) function cudaFree(buffer)  bind(C, name="cudaFree")
        use iso_c_binding
        implicit none
        type (c_ptr), value :: buffer
    end function cudaFree

end Interface
end module
module InterfaceCusparse  

interface
    integer(c_int) function cusparseCreate(cusparseHandle) &
                             bind(C,name="cusparseCreate")

        use iso_c_binding
        implicit none
        type(c_ptr) ::cusparseHandle
    end function cusparseCreate

    integer(4) function cusparseCreateCsr(descr, rows, cols, nnz, csrRowOffsets, &
                csrColInd, csrValues, csrRowOffsetsType, csrColIndType, idxBase, valueType) &
                bind(C,name="cusparseCreateCsr")
        use iso_c_binding
        type(c_ptr) :: descr
        integer(kind=c_int64_t), value :: rows, cols, nnz
        type(c_ptr), value :: csrRowOffsets, csrColInd
        type(c_ptr), value :: csrValues
        integer(c_int), value :: csrRowOffsetsType, csrColIndType, idxBase, valueType
    end

    integer(c_int) function cusparseDestroy(cusparseHandle) bind(C,name="cusparseDestroy")

        use iso_c_binding
        implicit none
        type(c_ptr),value::cusparseHandle
    end function cusparseDestroy

    integer(c_int) function cusparseDestroyMatDescr(descrA) bind(C,name="cusparseDestroyMatDescr")

        use iso_c_binding
        implicit none
        type(c_ptr), value:: descrA
    end function cusparseDestroyMatDescr

    integer(c_int) function cusparseDestroyDnVec(descr) bind(C,name="cusparseDestroyDnVec")
 
        use iso_c_binding
        type(c_ptr), value :: descr
    end function cusparseDestroyDnVec

    integer(4) function cusparseDestroySpMat(descr) bind(C,name="cusparseDestroySpMat")
 
        use iso_c_binding
        type(c_ptr), value :: descr
    end function cusparseDestroySpMat

    integer(4) function cusparseCreateDnVec(descr, size, values, valueType)  &
                bind(C,name="cusparseCreateDnVec")
        use iso_c_binding
        type(c_ptr) :: descr
        integer(kind=c_int64_t), value ::  size
        type(c_ptr), value :: values
        integer(c_int), value  :: valueType
    end

    integer(4) function cusparseSpMV_bufferSize(handle, opA, alpha, matA, vecX, beta, vecY, computeType, alg, bufferSize) &
                bind(C,name="cusparseSpMV_bufferSize")
        use iso_c_binding
        type(c_ptr), value      :: handle
        integer(c_int), value   :: opA
!!        complex(c_float_complex)                  :: alpha, beta ! device or host variable
        complex(c_double_complex)                  :: alpha, beta ! device or host variable
!!        real(c_float)                 :: alpha, beta ! device or host variable
        type(c_ptr), value      :: matA
        type(c_ptr), value      :: vecX, vecY
        integer(c_int), value   :: computeType, alg
        integer(c_size_t)          :: bufferSize
    end

    integer(4) function cusparseSpMV(handle, opA, alpha, matA, vecX, beta, vecY, computeType, alg, buffer)  &
                bind(C,name="cusparseSpMV")
        use iso_c_binding
        type(c_ptr), value      :: handle
        integer(c_int), value   :: opA
!!        complex(c_float_complex)                :: alpha, beta ! device or host variable
        complex(c_double_complex)                 :: alpha, beta ! device or host variable
!!        real(c_float)                 :: alpha, beta ! device or host variable
        type(c_ptr), value      :: matA
        type(c_ptr), value      :: vecX
        type(c_ptr), value      :: vecY
        integer(c_int), value   :: computeType, alg
        type(c_ptr), value       :: buffer
    end
    
end interface
end module
module CudaTypes
    enum, bind(C) ! cusparseStatus_t
	    enumerator :: CUDA_R_16F  =  2 !!, /* real as a half */
	    enumerator :: CUDA_C_16F  =  6 !!, /* complex as a pair of half numbers */
	    enumerator :: CUDA_R_16BF = 14 !!, /* real as a nv_bfloat16 */
	    enumerator :: CUDA_C_16BF = 15 !!, /* complex as a pair of nv_bfloat16 numbers */
        enumerator :: CUDA_R_32F  =  0 !!, /* real as a float */
	    enumerator :: CUDA_C_32F  =  4 !!, /* complex as a pair of float numbers */
	    enumerator :: CUDA_R_64F  =  1 !!, /* real as a double */
	    enumerator :: CUDA_C_64F  =  5 !!, /* complex as a pair of double numbers */
	    enumerator :: CUDA_R_4I   = 16 !!, /* real as a signed 4-bit int */
	    enumerator :: CUDA_C_4I   = 17 !!, /* complex as a pair of signed 4-bit int numbers */
	    enumerator :: CUDA_R_4U   = 18 !!, /* real as a unsigned 4-bit int */
	    enumerator :: CUDA_C_4U   = 19 !!, /* complex as a pair of unsigned 4-bit int numbers */
	    enumerator :: CUDA_R_8I   =  3 !!, /* real as a signed 8-bit int */
	    enumerator :: CUDA_C_8I   =  7 !!, /* complex as a pair of signed 8-bit int numbers */
	    enumerator :: CUDA_R_8U   =  8 !!, /* real as a unsigned 8-bit int */
	    enumerator :: CUDA_C_8U   =  9 !!, /* complex as a pair of unsigned 8-bit int numbers */
	    enumerator :: CUDA_R_16I  = 20 !!, /* real as a signed 16-bit int */
	    enumerator :: CUDA_C_16I  = 21 !!, /* complex as a pair of signed 16-bit int numbers */
	    enumerator :: CUDA_R_16U  = 22 !!, /* real as a unsigned 16-bit int */
	    enumerator :: CUDA_C_16U  = 23 !!, /* complex as a pair of unsigned 16-bit int numbers */
	    enumerator :: CUDA_R_32I  = 10 !!, /* real as a signed 32-bit int */
	    enumerator :: CUDA_C_32I  = 11 !!, /* complex as a pair of signed 32-bit int numbers */
	    enumerator :: CUDA_R_32U  = 12 !!, /* real as a unsigned 32-bit int */
	    enumerator :: CUDA_C_32U  = 13 !!, /* complex as a pair of unsigned 32-bit int numbers */
	    enumerator :: CUDA_R_64I  = 24 !!, /* real as a signed 64-bit int */
	    enumerator :: CUDA_C_64I  = 25 !!, /* complex as a pair of signed 64-bit int numbers */
	    enumerator :: CUDA_R_64U  = 26 !!, /* real as a unsigned 64-bit int */
	    enumerator :: CUDA_C_64U  = 27 !! /* complex as a pair of unsigned 64-bit int numbers */
    end enum
end module CudaTypes
module CuSparseTypes
    
USE, INTRINSIC :: ISO_C_BINDING
type cusparseHandle
 type(C_PTR) :: handle
end type cusparseHandle

type cusparseCsrsv2Info
 type(C_PTR) :: info
end type cusparseCsrsv2Info
type cusparseCsric02Info
 type(C_PTR) :: info
end type cusparseCsric02Info
type cusparseCsrilu02Info
 type(C_PTR) :: info
end type cusparseCsrilu02Info
type cusparseBsrsv2Info
 type(C_PTR) :: info
end type cusparseBsrsv2Info
type cusparseBsric02Info
 type(C_PTR) :: info
end type cusparseBsric02Info
type cusparseBsrilu02Info
 type(C_PTR) :: info
end type cusparseBsrilu02Info
type cusparseBsrsm2Info
 type(C_PTR) :: info
end type cusparseBsrsm2Info
type cusparseCsrgemm2Info
 type(C_PTR) :: info
end type cusparseCsrgemm2Info
type cusparseColorInfo
 type(C_PTR) :: info
end type cusparseColorInfo
type cusparseCsru2csrInfo
 type(C_PTR) :: info
end type cusparseCsru2csrInfo
type cusparseSpVecDescr
 type(C_PTR) :: descr
end type cusparseSpVecDescr
type cusparseDnVecDescr
 type(C_PTR) :: descr
end type cusparseDnVecDescr
type cusparseSpMatDescr
 type(C_PTR) :: descr
end type cusparseSpMatDescr
type cusparseDnMatDescr
 type(C_PTR) :: descr
end type cusparseDnMatDescr
    
    
! cuSPARSE status return values
enum, bind(C) ! cusparseStatus_t
 enumerator :: CUSPARSE_STATUS_SUCCESS=0
 enumerator :: CUSPARSE_STATUS_NOT_INITIALIZED=1
 enumerator :: CUSPARSE_STATUS_ALLOC_FAILED=2
 enumerator :: CUSPARSE_STATUS_INVALID_VALUE=3
 enumerator :: CUSPARSE_STATUS_ARCH_MISMATCH=4
 enumerator :: CUSPARSE_STATUS_MAPPING_ERROR=5
 enumerator :: CUSPARSE_STATUS_EXECUTION_FAILED=6
 enumerator :: CUSPARSE_STATUS_INTERNAL_ERROR=7
 enumerator :: CUSPARSE_STATUS_MATRIX_TYPE_NOT_SUPPORTED=8
 enumerator :: CUSPARSE_STATUS_ZERO_PIVOT=9
 enumerator :: CUSPARSE_STATUS_NOT_SUPPORTED=10
end enum
enum, bind(c) ! cusparsePointerMode_t
 enumerator :: CUSPARSE_POINTER_MODE_HOST = 0
 enumerator :: CUSPARSE_POINTER_MODE_DEVICE = 1
end enum
enum, bind(c) ! cusparseAction_t
 enumerator :: CUSPARSE_ACTION_SYMBOLIC = 0
 enumerator :: CUSPARSE_ACTION_NUMERIC = 1
end enum
enum, bind(C) ! cusparseMatrixType_t
 enumerator :: CUSPARSE_MATRIX_TYPE_GENERAL = 0
 enumerator :: CUSPARSE_MATRIX_TYPE_SYMMETRIC = 1
 enumerator :: CUSPARSE_MATRIX_TYPE_HERMITIAN = 2
 enumerator :: CUSPARSE_MATRIX_TYPE_TRIANGULAR = 3
end enum
enum, bind(C) ! cusparseFillMode_t
 enumerator :: CUSPARSE_FILL_MODE_LOWER = 0
 enumerator :: CUSPARSE_FILL_MODE_UPPER = 1
end enum
enum, bind(C) ! cusparseDiagType_t
 enumerator :: CUSPARSE_DIAG_TYPE_NON_UNIT = 0
 enumerator :: CUSPARSE_DIAG_TYPE_UNIT = 1
end enum
enum, bind(C) ! cusparseIndexBase_t
 enumerator :: CUSPARSE_INDEX_BASE_ZERO = 0
 enumerator :: CUSPARSE_INDEX_BASE_ONE = 1
end enum
enum, bind(C) ! cusparseOperation_t
 enumerator :: CUSPARSE_OPERATION_NON_TRANSPOSE = 0
 enumerator :: CUSPARSE_OPERATION_TRANSPOSE = 1
 enumerator :: CUSPARSE_OPERATION_CONJUGATE_TRANSPOSE = 2
end enum
enum, bind(C) ! cusparseDirection_t
 enumerator :: CUSPARSE_DIRECTION_ROW = 0
 enumerator :: CUSPARSE_DIRECTION_COLUMN = 1
end enum
enum, bind(C) ! cusparseHybPartition_t
 enumerator :: CUSPARSE_HYB_PARTITION_AUTO = 0
 enumerator :: CUSPARSE_HYB_PARTITION_USER = 1
 enumerator :: CUSPARSE_HYB_PARTITION_MAX = 2
end enum
enum, bind(C) ! cusparseSolvePolicy_t
 enumerator :: CUSPARSE_SOLVE_POLICY_NO_LEVEL = 0
 enumerator :: CUSPARSE_SOLVE_POLICY_USE_LEVEL = 1
end enum
enum, bind(C) ! cusparseSideMode_t
 enumerator :: CUSPARSE_SIDE_LEFT = 0
 enumerator :: CUSPARSE_SIDE_RIGHT = 1
end enum
enum, bind(C) ! cusparseColorAlg_t
 enumerator :: CUSPARSE_COLOR_ALG0 = 0
 enumerator :: CUSPARSE_COLOR_ALG1 = 1
end enum
enum, bind(C) ! cusparseAlgMode_t;
 enumerator :: CUSPARSE_ALG0 = 0
 enumerator :: CUSPARSE_ALG1 = 1
 enumerator :: CUSPARSE_ALG_NAIVE = 0
 enumerator :: CUSPARSE_ALG_MERGE_PATH = 1
end enum
enum, bind(C) ! cusparseCsr2CscAlg_t;
 enumerator :: CUSPARSE_CSR2CSC_ALG1 = 1
 enumerator :: CUSPARSE_CSR2CSC_ALG2 = 2
end enum
enum, bind(C) ! cusparseFormat_t;
 enumerator :: CUSPARSE_FORMAT_CSR = 1
 enumerator :: CUSPARSE_FORMAT_CSC = 2
 enumerator :: CUSPARSE_FORMAT_COO = 3
 enumerator :: CUSPARSE_FORMAT_COO_AOS = 4
end enum
enum, bind(C) ! cusparseOrder_t;
 enumerator :: CUSPARSE_ORDER_COL = 1
 enumerator :: CUSPARSE_ORDER_ROW = 2
end enum
enum, bind(C) ! cusparseSpMVAlg_t;
 enumerator :: CUSPARSE_MV_ALG_DEFAULT = 0
 enumerator :: CUSPARSE_COOMV_ALG = 1
 enumerator :: CUSPARSE_CSRMV_ALG1 = 2
 enumerator :: CUSPARSE_CSRMV_ALG2 = 3
end enum
enum, bind(C) ! cusparseSpMMAlg_t;
 enumerator :: CUSPARSE_MM_ALG_DEFAULT = 0
 enumerator :: CUSPARSE_COOMM_ALG1 = 1
 enumerator :: CUSPARSE_COOMM_ALG2 = 2
 enumerator :: CUSPARSE_COOMM_ALG3 = 3
 enumerator :: CUSPARSE_CSRMM_ALG1 = 4
end enum
enum, bind(C) ! cusparseIndexType_t;
 enumerator :: CUSPARSE_INDEX_16U = 1
 enumerator :: CUSPARSE_INDEX_32I = 2
 enumerator :: CUSPARSE_INDEX_64I = 3
end enum

end module
program Main_test
use CudaTypes
use CuSparseTypes
use InterfaceCusparse
use InterfaceCUDA

    integer*4 hA_csrOffsets(5), hA_columns(9)
    integer*8 A_num_rows, A_num_cols, A_nnz
    integer ierr
    Integer, parameter  :: size_of_int=4
    Integer, parameter  :: size_of_real=4
    
!!    complex(c_float_complex)    hA_values(9), hX(4), hY(4), hY_result(4)
    complex(c_double_complex)    hA_values(9), hX(4), hY(4), hY_result(4)
    complex(c_double_complex)    alpha, beta
!!    complex(c_float_complex)    alpha, beta
    
    data      hA_csrOffsets / 1, 4, 5, 8, 10 /
    data      hA_columns / 1, 3, 4, 2, 1, 3, 4, 2, 4 /
    data      hA_values / (1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0), (5.0, 0.0),  & 
               (6.0, 0.0), (7.0, 0.0), (8.0, 0.0), (9.0, 0.0) /
    data      hX / (1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0) /
    data      hY / (0.0, 0.0), (1.0, 0.0), (1.0, 0.0), (0.0, 0.0) /
    data      hY_result / (19.0, 0.0), (8.0, 0.0), (51.0, 0.0), (52.0, 0.0) /
    
    !pointers to data
    type(C_PTR) :: AcsrOff_index, Acolumns_index, dAvalues_index, hX_index, hY_index
    
    ! Device memory management
    integer*4     :: AcsrOff_i_size, Acolumns_i_size, dAvalues_d_size, hX_d_size, hY_d_size
    integer*8     :: bufferSize
    type(C_PTR)   :: devPtr_AcsrOff, devPtr_Acolumns, devPtr_dAvalues, devPtr_dX, devPtr_dY, devPtr_Buffer
    
    integer*8 cudaMemcpyDeviceToHost, cudaMemcpyHostToDevice, cudaMemcpyDeviceToDevice
    parameter (cudaMemcpyHostToDevice=1)
    parameter (cudaMemcpyDeviceToHost=2)
    parameter (cudaMemcpyDeviceToDevice=3)

    integer*8 rows, cols, nnz, sizeVec
    integer*4 RowOffType, ColIndType, idxBase, valueType
    type(C_PTR)   :: devPtr_RowOff, devPtr_ColInd, devPtr_csrValues
    
    ! CUSPARSE APIs
    type(C_PTR)          handle, bl_handle
    type(C_PTR)          matA
    type(C_PTR)          vecX, vecY
    
    A_num_rows = 4
    A_num_cols = 4
    A_nnz      = 9
    alpha      = cmplx(1.0, 0.0)
    beta       = cmplx(0.0, 0.0)
    
    AcsrOff_i_size = sizeof(hA_csrOffsets(1:5))
    Acolumns_i_size = sizeof(hA_columns(1:9))
    dAvalues_d_size = sizeof(hA_values(1:9))
    hX_d_size = sizeof(hX(1:4))
    hY_d_size = sizeof(hY(1:4))
    
    AcsrOff_index = c_loc(hA_csrOffsets)
    Acolumns_index = c_loc(hA_columns)
    dAvalues_index = c_loc(hA_values)
    hX_index = c_loc(hX)
    hY_index = c_loc(hY)
    
    
    ierr = cudaMalloc(devPtr_AcsrOff, AcsrOff_i_size)
    ierr = cudaMalloc(devPtr_Acolumns, Acolumns_i_size)
    ierr = cudaMalloc(devPtr_dAvalues, dAvalues_d_size)
    ierr = cudaMalloc(devPtr_dX, hX_d_size)
    ierr = cudaMalloc(devPtr_dY, hY_d_size)
      
    ierr = cudaMemcpy(devPtr_AcsrOff,AcsrOff_index,AcsrOff_i_size,cudaMemcpyHostToDevice)
    ierr = cudaMemcpy(devPtr_Acolumns,Acolumns_index,Acolumns_i_size,cudaMemcpyHostToDevice)
    ierr = cudaMemcpy(devPtr_dAvalues,dAvalues_index,dAvalues_d_size,cudaMemcpyHostToDevice)
    ierr = cudaMemcpy(devPtr_dX,hX_index,hX_d_size,cudaMemcpyHostToDevice)
    ierr = cudaMemcpy(devPtr_dY,hY_index,hY_d_size,cudaMemcpyHostToDevice)
    if (ierr /= CUSPARSE_STATUS_SUCCESS) goto 9000

    ierr = cusparseCreate(handle)
    if (ierr /= CUSPARSE_STATUS_SUCCESS) goto 9000
    
    ! Create sparse matrix A in CSR format
    ierr = cusparseCreateCsr(matA, A_num_rows, A_num_cols, A_nnz,                      &
                                      devPtr_AcsrOff, devPtr_Acolumns, devPtr_dAvalues,  &
                                      CUSPARSE_INDEX_32I, CUSPARSE_INDEX_32I,            &
                                      CUSPARSE_INDEX_BASE_ONE, CUDA_C_64F)
    if (ierr /= CUSPARSE_STATUS_SUCCESS) goto 9000

    !Create dense vector X
    ierr = cusparseCreateDnVec(vecX, A_num_cols, devPtr_dX, CUDA_C_64F)
    !Create dense vector y
    ierr = cusparseCreateDnVec(vecY, A_num_rows, devPtr_dY, CUDA_C_64F)
    
    !allocate an external buffer if needed
    ierr = cusparseSpMV_bufferSize(handle, CUSPARSE_OPERATION_NON_TRANSPOSE,    &
                                   Alpha, matA, vecX, Beta, vecY, CUDA_C_64F,   &
                                   CUSPARSE_MV_ALG_DEFAULT, bufferSize) 
    if (ierr /= CUSPARSE_STATUS_SUCCESS) goto 9000

    ierr = cudaMalloc(devPtr_Buffer, int(bufferSize)*16) 
    if (ierr /= CUSPARSE_STATUS_SUCCESS) goto 9000

    !execute SpMV
    ierr = cusparseSpMV(handle, CUSPARSE_OPERATION_NON_TRANSPOSE,    &
                        Alpha, matA, vecX, Beta, vecY, CUDA_C_64F,   &
                        CUSPARSE_MV_ALG_DEFAULT, devPtr_Buffer) 
    if (ierr /= CUSPARSE_STATUS_SUCCESS) goto 9000

    !device result check
    ierr = cudaMemcpy(hY_index, devPtr_dY, hY_d_size, cudaMemcpyDeviceToHost)
    
    write(*,*) (hY(i), i=1,A_num_rows)

    !destroy matrix/vector descriptors
    ierr = cusparseDestroySpMat(matA)
    ierr = cusparseDestroyDnVec(vecX)
    ierr = cusparseDestroyDnVec(vecY)
    ierr = cusparseDestroy(handle)
    
    !device memory deallocation
    ierr = cudaFree(devPtr_Buffer)
    ierr = cudaFree(devPtr_AcsrOff)
    ierr = cudaFree(devPtr_Acolumns)
    ierr = cudaFree(devPtr_dAvalues)
    ierr = cudaFree(devPtr_dX)
    ierr = cudaFree(devPtr_dY)

9000 if (ierr /= CUSPARSE_STATUS_SUCCESS) write(*,*) "Error occurred"
     end``

**Comment by federico-busato** [comment]
are you able to reproduce the error in C/C++?

**Comment by PvandenBosch** [comment]
I'm affraid not. I don't have a C/C++ compiler installed

**Comment by federico-busato** [comment]
I'm trying to understand where the issue is. We deeply test CUDA_C_64F in the standard test cases, so I would exclude an issue with the routine itself. It could be something related to the compiler or the CUDA toolkit. Can you please try to use a more recent version of the Intel compiler and of the CUDA Toolkit? also, at which line do you get the error?

**Comment by PvandenBosch** [comment]
The error is at the line:
ierr = cusparseSpMV(handle, CUSPARSE_OPERATION_NON_TRANSPOSE,    &
                    Alpha, matA, vecX, Beta, vecY, CUDA_C_64F,   &
                    CUSPARSE_MV_ALG_DEFAULT, devPtr_Buffer) 
So, by calling cusparseSpMv. 
I will try to compile it with the Intel 2019 compiler, in the coming days.

**Comment by PvandenBosch** [comment]
I did the test with the Intel 2020.2.254 Fortran compiler and with CUDA toolkit 11.6 and found the same result

I also did some tests with C/C++. Running the standard example and the example modified for CUDA_C_32F gives correct results. However changing the datatype to CUDA_C_64F runs in an exception after calling cusparseSpMV. The C/C++code for the test with CUDA_C_64F is below.

`#include <cuda_runtime_api.h> // cudaMalloc, cudaMemcpy, etc.
#include <cusparse.h>         // cusparseSpMV
#include <stdio.h>            // printf
#include <stdlib.h>           // EXIT_FAILURE
#include <complex>

#define CHECK_CUDA(func)                                                       \
{                                                                              \
    cudaError_t status = (func);                                               \
    if (status != cudaSuccess) {                                               \
        printf("CUDA API failed at line %d with error: %s (%d)\n",             \
               __LINE__, cudaGetErrorString(status), status);                  \
        return EXIT_FAILURE;                                                   \
    }                                                                          \
}

#define CHECK_CUSPARSE(func)                                                   \
{                                                                              \
    cusparseStatus_t status = (func);                                          \
    if (status != CUSPARSE_STATUS_SUCCESS) {                                   \
        printf("CUSPARSE API failed at line %d with error: %s (%d)\n",         \
               __LINE__, cusparseGetErrorString(status), status);              \
        return EXIT_FAILURE;                                                   \
    }                                                                          \
}

int main(void) {
    // Host problem definition
    const int A_num_rows = 4;
    const int A_num_cols = 4;
    const int A_nnz = 9;
    int       hA_csrOffsets[] = { 0, 3, 4, 7, 9 };
    int       hA_columns[] = { 0, 2, 3, 1, 0, 2, 3, 1, 3 };
    std::complex<double>     hA_values[] = { {1.0f,0.0f}, {2.0f,0.0f}, {3.0f,0.0f}, {4.0f,0.0f}, {5.0f,0.0f},
        {6.0f,0.0f}, {7.0f,0.0f}, {8.0f,0.0f}, {9.0f,0.0f} };
    std::complex<double>     hX[] = { {1.0f,0.0f}, {2.0f,0.0f}, {3.0f,0.0f}, {4.0f,0.0f} };
    std::complex<double>     hY[] = { {0.0f,0.0f}, {0.0f,0.0f}, {0.0f,0.0f}, {0.0f,0.0f} };
    std::complex<double>     hY_result[] = { {19.0f,0.0f}, {8.0f,0.0f}, {51.0f,0.0f}, {52.0f,0.0f} };
    std::complex<double>   alpha = { 1.f,0.f };
    std::complex<double>   beta = { 0.f,0.f };
    //--------------------------------------------------------------------------
    // Device memory management
    int* dA_csrOffsets, * dA_columns;
    float* dA_values, * dX, * dY;
     CHECK_CUDA(cudaMalloc((void**)&dA_csrOffsets,
        (A_num_rows + 1) * sizeof(int)))
        CHECK_CUDA(cudaMalloc((void**)&dA_columns, A_nnz * sizeof(int)))
        CHECK_CUDA(cudaMalloc((void**)&dA_values, A_nnz * sizeof(std::complex<double>)))
        CHECK_CUDA(cudaMalloc((void**)&dX, A_num_cols * sizeof(std::complex<double>)))
        CHECK_CUDA(cudaMalloc((void**)&dY, A_num_rows * sizeof(std::complex<double>)))

        CHECK_CUDA(cudaMemcpy(dA_csrOffsets, hA_csrOffsets,
            (A_num_rows + 1) * sizeof(int),
            cudaMemcpyHostToDevice))
        CHECK_CUDA(cudaMemcpy(dA_columns, hA_columns, A_nnz * sizeof(int),
            cudaMemcpyHostToDevice))
        CHECK_CUDA(cudaMemcpy(dA_values, hA_values, A_nnz * sizeof(std::complex<double>),
            cudaMemcpyHostToDevice))
        CHECK_CUDA(cudaMemcpy(dX, hX, A_num_cols * sizeof(std::complex<double>),
            cudaMemcpyHostToDevice))
        CHECK_CUDA(cudaMemcpy(dY, hY, A_num_rows * sizeof(std::complex<double>),
            cudaMemcpyHostToDevice))
        //--------------------------------------------------------------------------
        // CUSPARSE APIs
        cusparseHandle_t     handle = NULL;
    cusparseSpMatDescr_t matA;
    cusparseDnVecDescr_t vecX, vecY;
    void* dBuffer = NULL;
    size_t               bufferSize = 0;
    CHECK_CUSPARSE(cusparseCreate(&handle))
        // Create sparse matrix A in CSR format
        CHECK_CUSPARSE(cusparseCreateCsr(&matA, A_num_rows, A_num_cols, A_nnz,
            dA_csrOffsets, dA_columns, dA_values,
            CUSPARSE_INDEX_32I, CUSPARSE_INDEX_32I,
            CUSPARSE_INDEX_BASE_ZERO, CUDA_C_64F))
        // Create dense vector X
        CHECK_CUSPARSE(cusparseCreateDnVec(&vecX, A_num_cols, dX, CUDA_C_64F))
        // Create dense vector y
        CHECK_CUSPARSE(cusparseCreateDnVec(&vecY, A_num_rows, dY, CUDA_C_64F))
        // allocate an external buffer if needed
        CHECK_CUSPARSE(cusparseSpMV_bufferSize(
            handle, CUSPARSE_OPERATION_NON_TRANSPOSE,
            &alpha, matA, vecX, &beta, vecY, CUDA_C_64F,
            CUSPARSE_MV_ALG_DEFAULT, &bufferSize))
        CHECK_CUDA(cudaMalloc(&dBuffer, bufferSize))

        // execute SpMV
        CHECK_CUSPARSE(cusparseSpMV(handle, CUSPARSE_OPERATION_NON_TRANSPOSE,
            &alpha, matA, vecX, &beta, vecY, CUDA_C_64F,
            CUSPARSE_MV_ALG_DEFAULT, dBuffer))

        // destroy matrix/vector descriptors
        CHECK_CUSPARSE(cusparseDestroySpMat(matA))
        CHECK_CUSPARSE(cusparseDestroyDnVec(vecX))
        CHECK_CUSPARSE(cusparseDestroyDnVec(vecY))
        CHECK_CUSPARSE(cusparseDestroy(handle))
        //--------------------------------------------------------------------------
        // device result check
        CHECK_CUDA(cudaMemcpy(hY, dY, A_num_rows * sizeof(std::complex<double>),
            cudaMemcpyDeviceToHost))
        int correct = 1;
    for (int i = 0; i < A_num_rows; i++) {
        if (hY[i] != hY_result[i]) { // direct floating point comparison is not
            correct = 0;             // reliable
            break;
        }
    }
    if (correct)
        printf("spmv_csr_example test PASSED\n");
    else
        printf("spmv_csr_example test FAILED: wrong result\n");
    //--------------------------------------------------------------------------
    // device memory deallocation
    CHECK_CUDA(cudaFree(dBuffer))
        CHECK_CUDA(cudaFree(dA_csrOffsets))
        CHECK_CUDA(cudaFree(dA_columns))
        CHECK_CUDA(cudaFree(dA_values))
        CHECK_CUDA(cudaFree(dX))
        CHECK_CUDA(cudaFree(dY))
        return EXIT_SUCCESS;
}

**Comment by federico-busato** [comment]
wait. You are using `std::complex` (without an explicit template parameter) which represents a single-precision complex number and not a double-precision complex number (`CUDA_C_64F`).
I strongly suggest using CUDA `cuDoubleComplex` instead. Please check the following example that I tested and works correctly
[spmv_csr_example_complex.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/7953375/spmv_csr_example_complex.zip)

**Comment by PvandenBosch** [comment]
Sorry, but apparently something went wrong while copying the code. I did used the double template (see below).

I just tried your example with the cuDoubleComplex and that works fine. 
The problem is that I can't use the cuDoubleComplex in Fortran. I think the Fortran Complex(c_double_complex) is equivalent to the C std::complex<double> which runs in an exception. 
So the question is what to use in Fortran.


`    std::complex<double>     hA_values[] = { {1.0f,0.0f}, {2.0f,0.0f}, {3.0f,0.0f}, {4.0f,0.0f}, {5.0f,0.0f},
        {6.0f,0.0f}, {7.0f,0.0f}, {8.0f,0.0f}, {9.0f,0.0f} };
    std::complex<double>     hX[] = { {1.0f,0.0f}, {2.0f,0.0f}, {3.0f,0.0f}, {4.0f,0.0f} };
    std::complex<double>     hY[] = { {0.0f,0.0f}, {0.0f,0.0f}, {0.0f,0.0f}, {0.0f,0.0f} };
    std::complex<double>     hY_result[] = { {19.0f,0.0f}, {8.0f,0.0f}, {51.0f,0.0f}, {52.0f,0.0f} };
    std::complex<double>   alpha = { 1.f,0.f };
    std::complex<double>   beta = { 0.f,0.f };

        CHECK_CUDA(cudaMalloc((void**)&dA_values, A_nnz * sizeof(std::complex<double>)))
        CHECK_CUDA(cudaMalloc((void**)&dX, A_num_cols * sizeof(std::complex<double>)))
        CHECK_CUDA(cudaMalloc((void**)&dY, A_num_rows * sizeof(std::complex<double>)))


`

**Comment by PvandenBosch** [comment]
Again the template is removed. I don't know how that happens.

    std::complex<double>     hA_values[] = { {1.0f,0.0f}, {2.0f,0.0f}, {3.0f,0.0f}, {4.0f,0.0f}, {5.0f,0.0f},
        {6.0f,0.0f}, {7.0f,0.0f}, {8.0f,0.0f}, {9.0f,0.0f} };
    std::complex<double>     hX[] = { {1.0f,0.0f}, {2.0f,0.0f}, {3.0f,0.0f}, {4.0f,0.0f} };
    std::complex<double>     hY[] = { {0.0f,0.0f}, {0.0f,0.0f}, {0.0f,0.0f}, {0.0f,0.0f} };
    std::complex<double>     hY_result[] = { {19.0f,0.0f}, {8.0f,0.0f}, {51.0f,0.0f}, {52.0f,0.0f} };
    std::complex<double>   alpha = { 1.f,0.f };
    std::complex<double>   beta = { 0.f,0.f };

**Comment by federico-busato** [comment]
it should be `complex(8)`. see https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/data-types-constants-and-variables/intrinsic-data-types/complex-data-types/complex-8-or-double-complex-constants.html

**Comment by PvandenBosch** [comment]
I tried complex(8), but it also runs in memory access violation like complex(c_double_complex) does.

For the C/C++ program I replaced all cuDoubleComplex by std::complex<double> and it also runs in an exception.

![image](https://user-images.githubusercontent.com/97903331/151552340-da20b557-1613-4f49-82fc-904368116643.png)

**Comment by federico-busato** [comment]
We don't ensure any compatibility with `std::complex`. The CUDA math libraries use a pure C interface, so `std::complex` is not even tested. It could have a different memory layout and causes application crash for this reason

**Comment by PvandenBosch** [comment]
Remains that I can't use cuDoubleComplex from Fortran.

**Comment by bdudleback** [comment]
If you can believe the error, the cusparse library is reading from location -1_8.  I would print out the type(c_ptr) arguments you are passing to the library routine and see if one of them looks bad.  Also, I think cudaMalloc takes a size_t, which is not an int.
