### ISSUE TITLE
2:4 sparsity speedup not expected

### ISSUE THREAD

**Issue by KaizhaoLiang** [NVIDIA/CUDALibrarySamples#57]
On an A100 with CUDA Version 11.5 and Driver version 495.29.05.
The cuSparselt example of size m=n=k=4096 measures at 0.545792 ms, with fp16.
The cutlass gemm of the same size is profiled at 0.607959 ms, with fp 16.
This only gives 1.1x at best.
The blogpost claimed something smaller than this could get 1.5x speedup over dense and as size grows the speedup also increases? I wonder what setting are those data points measured in and what metric was used to report the speedup (was it sample/s/watt)?

**Comment by fbusato** [comment]
yes, this is expected for small sizes. The blog reported the comparison with cuBLAS including large matrices by using the execution time as metric

**Comment by KaizhaoLiang** [comment]
but this size is technically bigger than the one that is reported in the blog post right?

**Comment by fbusato** [comment]
the blog reports the performance for M+N=4096, K=10240. Also, we measured the performance in a very special and controlled environment to provide accurate results. A few examples. It is easy is to reach peak power utilization, thermal throttling, clock instability, etc. on standard GPU which affects the accuracy of the measurements. Finally, also the CUDA toolkit (e.g. cuBLAS) and the driver versions could affect the measurements.

**Comment by KaizhaoLiang** [comment]
Thanks for the clarification. One more question: when you said M + N = 4096, you meant any M and N that satisfied this equality (e.g. M = 1 and N = 4095) or there is a specific size that is preferred.

**Comment by fbusato** [comment]
Sorry, I meant M=N. I fixed the comment

**Comment by KaizhaoLiang** [comment]
I did another quick measurement with the above size, which seems to be still around 1.2x speedup. I guess it really depends on a lot of different factors. Do you happen to know which CUDA driver version was used in the blog? I am using the latest one so I assume it might be different.

**Comment by fbusato** [comment]
We used the driver included in the CUDA toolkit 11.0 as well as the cuBLAS library. The speedup you are measuring could be also due to recent improvements in dense GEMM or a different clock setting of the GPU. If I remember correctly, we used the max clock
