### ISSUE TITLE
Question about cusparseGetColorAlgs

### ISSUE THREAD

**Issue by vmiheer** [NVIDIA/CUDALibrarySamples#6]
Maybe this is not the correct place to ask this question, but I couldn't find documentation of `cusparseGetColorAlgs`. I am trying to find a function which would tell me which algorithm is used by `cusparseSpMM` when called with `CUSPARSE_SPMM_ALG_DEFAULT`?

**Comment by vmiheer** [comment]
Please let me know if I should be asking this at some other place 😊.

**Comment by maheshkha** [comment]
`cusparseGetColorAlgs` - located in CUDA toolkit include file `cusparse.h` 

`/usr/local/cuda-11.0/include$ ls cusparse.h `
`cusparse.h`


We recommend professional CUDA developers to become registered developers, which enables them to file and get feedback on bugs at the following link.

https://developer.nvidia.com/

For general discussion of setting up development environments, algorithms, optimizations and so on, please visit the [DevZone forums](https://devtalk.nvidia.com/).
