### ISSUE TITLE
spmm_csr_batched example has wrong results!

### ISSUE THREAD

**Issue by lhl2017** [NVIDIA/CUDALibrarySamples#65]
There are wrong results in the [spmm_csr_batched](https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSE/spmm_csr_batched) example.

As I know, batched SPMM is `batched Sparse MatA x batched Dense MatB = batched Dense MatC`. However,  In the example, the first batch of multiplication MatA broadcasts to the batched MatB for multiplication. Just like the figure in the README. I checked that the real results are` hA_values1[] x hB2[]`

Am I misunderstanding the batched SPMM? If not, I think `cusparseCsrSetStrideBatch ` function doesn't work. 

Would you please check this example? Thanks!

Device: RTX3090
Cuda: 11.3

**Comment by fbusato** [comment]
Your understanding of batched SpMM is correct but it is not the only method available. You can have:
- multiple A, multiple  B,  multiple C
- single A, multiple B, multiple C
- multiple A, single B,  multiple C

We proposed this example to be as simple as possible. For CSR SpMM, you can have multiple A matrices but the number of non-zero entries per row must be the same across the batch. While for COO SpMM, the only restriction is to have the same number of non-zero entries (globally).

**Comment by lhl2017** [comment]
>

**Comment by lhl2017** [comment]
Thank you for your kind reply. 

So, how should I change the example for batched CSR SpMM?

Actually, the example is written as the first case you mentioned(multiple A, multiple B, multiple C). However, it works as the second case(single A, multiple B, multiple C).  
I still think `cusparseCsrSetStrideBatch` does not work correctly.

**Comment by fbusato** [comment]
ok, now I'm understanding the issue. The image in the README shows the case (2) "single A, multiple B, multiple C", while the code shows the behavior of (1) "multiple A, multiple B, multiple C" see line https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuSPARSE/spmm_csr_batched/spmm_csr_batched_example.c#L171. I will fix it soon.
To be honest, I don't understand what do you mean with
> Actually, the example is written as the first case you mentioned(multiple A, multiple B, multiple C). However, it works as the second case(single A, multiple B, multiple C).

The code shows the behavior for the case (1) by using `hA_values1/hA_values2`, `hB1/hB2`, and `hC1/hC2`

**Comment by lhl2017** [comment]
I mean `make test` shows **spmm_csr_batched_example test FAILED: wrong results**. 
Although the code behavior for (1), actually the results are for behavior for (2). I checked the results by printing the hC1 and hC2. I don't know why it is.

**Comment by lhl2017** [comment]
It passed with the CUDA 11.6 but failed with the 11.3.

**Comment by fbusato** [comment]
yes, it is expected. Batches of sparse matrices are supported in CUDA 11.6u1, see https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cusparse-11.6.1. I will fix the example README
