### ISSUE TITLE
how to print the logging

### ISSUE THREAD

**Issue by minghaoBD** [NVIDIA/CUDALibrarySamples#66]
Hi, I have a question about the logging part in the cuSparse documentation. I did the following steps but no logging is found.

1. compile the example here: https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSE/spgemm
2. export CUSPARSE_LOG_LEVEL=5, according here: https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-logging
3. ./spgemm_example

My cuda is 11.3 and cuSparse is 11.6.0. I suppose the environment should be right based on the documentation. I have no idea what I did wrong. Could you help check on it?

**Comment by fbusato** [comment]
Hi, cuSPARSE logging APIs and functionalities have been introduced in CUDA 11.5 Update 1. See [cuSPARSE Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cusparse-11.5.1)
Your steps are correct.
