### ISSUE TITLE
nvJPEG2000 NVJPEG2K_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by cracy3m** [NVIDIA/CUDALibrarySamples#69]
Hi,
I got error  NVJPEG2K_STATUS_INTERNAL_ERROR when invoke nvjpeg2kEncode(), can anyone help?

My code is refer Quick Start Guide in nvJPEG2000 Documentation :
/****************************************/
// env:
// nvJPEG2000 library version is v0.5.0.25
// vs2017
// cuda11.6

unsigned short *inbuf = new unsigned short[1571*512];
    for (size_t i = 0; i < 1571*512; ++i) {
        inbuf[i] = static_cast<unsigned short>(qrand()%(65536));  //  if no generate random value , error do not occured
    }

nvjpeg2kEncoder_t enc_handle = nullptr;
    nvjpeg2kEncodeState_t enc_state = nullptr;
    nvjpeg2kEncodeParams_t enc_params = nullptr;

    nvjpeg2kEncoderCreateSimple(&enc_handle);
    nvjpeg2kEncodeStateCreate(enc_handle,&enc_state);
    nvjpeg2kEncodeParamsCreate(&enc_params);

    nvjpeg2kImageComponentInfo_t image_comp_info;

    image_comp_info.component_width = 1571;
    image_comp_info.component_height = 512;
    image_comp_info.precision = 16;
    image_comp_info.sgn = 0;

    void *pixel_data;
    size_t pitch_in_bytes;
    cudaMallocPitch(&pixel_data,&pitch_in_bytes,
                    image_comp_info.component_width * 2,
                    image_comp_info.component_height);

    nvjpeg2kImage_t input_image;
    input_image.pixel_data = &pixel_data;
    input_image.pixel_type = NVJPEG2K_UINT16;
    input_image.pitch_in_bytes = &pitch_in_bytes;
    input_image.num_components = 1;

    nvjpeg2kEncodeConfig_t enc_config;
    memset(&enc_config, 0, sizeof(enc_config));
    enc_config.stream_type      =  NVJPEG2K_STREAM_JP2; // the bitstream will be in JP2 container format
    enc_config.color_space      =  NVJPEG2K_COLORSPACE_GRAY; // input image is in gray format
    enc_config.image_width      =  image_comp_info.component_width;
    enc_config.image_height     =  image_comp_info.component_height;
    enc_config.num_components   =  1;
    enc_config.image_comp_info  =  &image_comp_info;
    enc_config.code_block_w     =  64;
    enc_config.code_block_h     =  64;
    enc_config.irreversible     =  1;
    enc_config.mct_mode         =  enc_config.color_space == NVJPEG2K_COLORSPACE_SRGB ? 1 : 0;
    enc_config.prog_order       =  NVJPEG2K_LRCP;
    enc_config.num_resolutions  =  6;

    nvjpeg2kStatus_t status = nvjpeg2kEncodeParamsSetEncodeConfig(enc_params, &enc_config);

    double target_psnr = 100;
    // status = nvjpeg2kEncodeParamsSetQuality(enc_params, target_psnr); // uncomment this, error go away ，but is it mean must use lossy compression?

    cudaMemcpy2D(input_image.pixel_data[0],
            input_image.pitch_in_bytes[0],
            inbuf, 2 * image_comp_info.component_width ,
            image_comp_info.component_width * 2,
            image_comp_info.component_height,
            cudaMemcpyHostToDevice
            );

    status = nvjpeg2kEncode(enc_handle, enc_state, enc_params, &input_image, nullptr); // NVJPEG2K_STATUS_INTERNAL_ERROR occured

    // set the compressed_data buffer to NULL to retrieve the bitstream size
    size_t compressed_size;
    status = nvjpeg2kEncodeRetrieveBitstream(enc_handle, enc_state, nullptr,
                                             &compressed_size,
                                             nullptr);

    // allocate output buffer
    unsigned char *compressed_data = new unsigned char [compressed_size];
    status = nvjpeg2kEncodeRetrieveBitstream(enc_handle, enc_state, compressed_data,
                                             &compressed_size,
                                             nullptr);
/****************************************/

**Comment by maheshkha** [comment]
Hi, 
Completely random data streams cannot be compressed in lossless compression. 

If you test with real data set then compress with lossless will work. 

Can you provide use case for random data streams?

**Comment by cracy3m** [comment]
Thanks reply,
It's also occurs when I set enc_config.irreversible  to 1 and psnr>100+ (dose it mean lossy?) 
I just test the library performance vs OpenCV, and use the random data set for input, then the error occurred.
My project is not random data streams use case, but most data of image(OCT image after FFT) may random distribute in small range,I am not sure this issue will casue problem or not.

OpenCV use rates of layers (tcp_rates[100]) to control compression ratio, Is there API like OpenCV to  control compression ratio?

**Comment by maheshkha** [comment]
Encoder setting `enc_config.irreversible to 1 and psnr>100`
Yes, it is lossy compression, you will not able to perfectly reconstruct the image. But the bitstream will not compressed as a input is random.

In nvJPEG2k library, Control compression ratio approach is slower than PSNR approach. 

Can you check by setting PSNR values between 50-60 that fulfill your lossy encode need?

**Comment by cracy3m** [comment]
Thanks, I got it.
In my test case , The compression ratio can be less than 50% when The PSNR set to 70 (twice time longer than PNG format compression by cpu at block size set to 64).
I think I should use PNG format lossless compression rather then nvJPEG2000, and just extent SSD hardware -,- ;



At 2022-04-22 13:57:40, "Mahesh Khadatare" ***@***.***> wrote:

Encoder setting enc_config.irreversible to 1 and psnr>100
Yes, it is lossy compression, you will not able to perfectly reconstruct the image. But the bitstream will not compressed as a input is random.

In nvJPEG2k library, Control compression ratio approach is slower than PSNR approach.

Can you check by setting PSNR values between 50-60 that fulfill your lossy encode need?

**Comment by maheshkha** [comment]
Thank you for input. Closing this issue.
