### ISSUE TITLE
How to calculate J'J, where J(mxn, m!=n) is a sparse matrix?

### ISSUE THREAD

**Issue by LogWell** [NVIDIA/CUDALibrarySamples#7]
I changed the code to
```
    CHECK_CUSPARSE(cusparseSpGEMM_workEstimation(handle, OP_T, OP_N,
                                                 &alpha, mat_J, mat_J, &beta, mat_JTJ,
                                                 CUDA_R_32F, CUSPARSE_SPGEMM_DEFAULT,
                                                 spgemmDesc, &bufferSize1, dBuffer1));
```
with error
```
** On entry to cusparseSpGEMM_workEstimation() dimension mismatch: matA->cols != matB->rows
```

In fact, I pass in coo format of matrix `J` with residual vector `R`,  I want to calculate `J'J`, and `J'R`, is there any efficient pipeline?

**Comment by LogWell** [comment]
[Note](https://docs.nvidia.com/cuda/cusparse/#cusparse-generic-function-spgemm) here,  

> Only opA, opB equal to CUSPARSE_OPERATION_NON_TRANSPOSE are supported

Does that mean that I need to assemble the coo coordinates of J into two different matrices A and B to compute?

**Comment by fbusato** [comment]
cusparseSpGEMM currently supports CSR format (COO is not supported) and CUSPARSE_OPERATION_NON_TRANSPOSE for A and B matrices. If you want to perform A^T, you have to pre-compute it by using cusparseCsr2cscEx2

**Comment by LogWell** [comment]
Notice that `A'A` is a symmetric matrix, so I can just calculate half of the elements to speed it up, and there's an example of [Eigen](https://stackoverflow.com/a/39621842/10636347), are there any relevant links in `cuda/cusparse`? 

Thank you very much~

**Comment by fbusato** [comment]
there no optimizations in this direction yet
