### ISSUE TITLE
NVJPEG2K_STATUS_JPEG_NOT_SUPPORTED

### ISSUE THREAD

**Issue by ysfu86** [NVIDIA/CUDALibrarySamples#70]
Hi:
When I use the Demo nvJPEG2000-Decoder to decode a jp2 image, I get an error when calling nvjpeg2kStreamParse, prompting NVJPEG2K_STATUS_JPEG_NOT_SUPPORTED. so i try to use openjpeg to decode it, it can successfully decode it , and I used openjpeg to dump the jp2 file information into a local file, then I found some items in the jp header that are different from the images it can decode,these items are shown below 
![微信图片_20220428163720](https://user-images.githubusercontent.com/92571125/165715675-b9ed318e-dabb-4574-aa1a-341951b66fe0.png)

ENV:
Win10 Home
NVDIA GeForce MX250
CUDA Version: 11.6
Driver Version: 511.65
nvJPEG2000 0.5.0

the file is below
[testin.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/8581190/testin.zip)

will this be supported in the future?
thanks!!!

**Comment by ysfu86** [comment]
This is the image after decoding by openjpeg
![testin](https://user-images.githubusercontent.com/92571125/165718572-6652b9ff-2d1c-49c7-a035-339ac091d50e.jpg)

**Comment by maheshkha** [comment]
Hi, Thank you reporting issue.
nvJPEG2000 currently support `code block style = 0` , test image bitstream has `code block style = 0x10`. We are targeting for next release. 
Do you have lot of test image with this cases? 
If you are generating the *.JP2 image - can you try to set `code block style = 0` and test with nvJPEG2000 decoder.

**Comment by ysfu86** [comment]
> Hi, Thank you for reporting issue. nvJPEG2000 currently support , test image bitstream has . We are targeting for next release. Do you have lot of test image with this cases? If you are generating the *.JP2 image - can you try to set and test with nvJPEG2000 decoder.`code block style = 0``code block style = 0x10``code block style = 0`

Thank you for your reply, when I do it as you said it can successfully decode it, but the image I get is from the camera and I've not seen the camera yet so far , so I'm not sure if it's possible to set the code block style. So I prefer to know when the next version will probably be available, thank you very much.

**Comment by maheshkha** [comment]
Next release schedule for Q3-22. Keep you posted.

**Comment by ysfu86** [comment]
ok, got it, thank you. If you have a beta version, remember to tell me, I'll be happy to test it. best wishes for you.

**Comment by Kadah** [comment]
My use case (loading existing texture assets in the Second Life client) has some images that fail to decode with this error. All textures I have checked, including ones that work without issue, are code block style of 0x4, so not the same cause as ysfu86's.

Been working though manually decoding some samples to find difference with the failing images and haven't found anything so far. Any insight would be appreciated.

Attached samples of both.

[Failed_Test_Textures.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/9664466/Failed_Test_Textures.zip)
[Working_Test_Textures.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/9664664/Working_Test_Textures.zip)

**Comment by ysfu86** [comment]
> Next release schedule for Q3-22. Keep you posted.

Is there a new version now?

**Comment by mkhadatare** [comment]
Hi @ysfu86 
Issue is fixed in develop branch.
Working on final release nvJPEG2K 0.7 posting date 03/22/23.

**Comment by ysfu86** [comment]
> Hi @ysfu86 Issue is fixed in develop branch. Working on final release nvJPEG2K 0.7 posting date 03/22/23.

That's great, I'm looking forward to it. By the way will the version 0.7 support other cblksty? or only the support 0x10 added?  @Kadah met the same problem as I met, but his cblksty was 0x04.

**Comment by maheshkha** [comment]
Hi @Kadah @ysfu86 

Our engineer test failed Test textures and found that image has num components = 5 (we support upto 4). 
We are working on this hopefully will make it to version 0.7.

**Comment by ysfu86** [comment]
Hi, @maheshkha, thank you very much, this issue has been solved in version 0.7. But I meet another problem in decoding other images, when I invoke streamparse it returns error  "NVJPEG failure: '#8' NVJPEG2K_STATUS_INTERNAL_ERROR".

[other.zip](https://github.com/NVIDIA/CUDALibrarySamples/files/11025654/other.zip)
