### ISSUE TITLE
Dllloadloaded Error on windows10, python37.

### ISSUE THREAD

**Issue by simpia** [NVIDIA/CUDALibrarySamples#75]
I use the nvtiff for python on windows10. And I can install the whl sucess. But when I import it will get an error. Can I get the source code of the nvtiff lib. And I want to refactoring it on my platform.

**Comment by maheshkha** [comment]
Hi Simpia, 
Please copy the nvtiff.lib and *.dll into the same working directory and try if this works.
Can you provide more details underline CUDA tools and error details?

**Comment by maheshkha** [comment]
Closing this issue.
