### ISSUE TITLE
Using SpGEMM for product and sum

### ISSUE THREAD

**Issue by shakedregev** [NVIDIA/CUDALibrarySamples#76]
I'm trying to modify [this](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuSPARSE/spgemm_reuse/spgemm_reuse_example.c) code to work with nonzero beta. Just trying to do C=AB+C but where C doesn't start empty. With the old SpGEMM function and old CUDA you couldn't do this unless you knew the nonzero structure of AB a-priori (and made C fit into that).  Is that the case with this version as well?

Does anyone have a nontrivial example of this with beta!=0 and the pre-known structure of the product not being used?

**Comment by fbusato** [comment]
>I'm trying to modify [this](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuSPARSE/spgemm_reuse/spgemm_reuse_example.c) code to work with nonzero beta. Just trying to do C=AB+C but where C doesn't start empty. With the old SpGEMM function and old CUDA you couldn't do this unless you knew the nonzero structure of AB a-priori (and made C fit into that). Is that the case with this version as well?

Yes, it is the same case. You need to know the sparsity structure of the C matrix

> Does anyone have a nontrivial example of this with beta!=0 and the pre-known structure of the product not being used?

Not really. You can take a look at the standard SpGEMM routine for beta != 0. This is the point where you can provide the pointers to the matrix C to update [https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuSPARSE/spgemm/spgemm_example.c#L206](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuSPARSE/spgemm/spgemm_example.c#L206)
