### ISSUE TITLE
Can d_bufferU and d_bufferL be shared in bicgstab_example.c?

### ISSUE THREAD

**Issue by jczhang07** [NVIDIA/CUDALibrarySamples#77]
https://github.com/NVIDIA/CUDALibrarySamples/blob/22d01d930423729489d4d10bd12986b6e8b01bf8/cuSPARSE/bicgstab/bicgstab_example.c#L240

**Comment by malmasri7** [comment]
The d_bufferU and d_bufferL cannot be shared. 
d_bufferU and d_bufferLbuffer hold different internal data structures specific for the upper and lower matrices, respectively.

**Comment by malmasri7** [comment]
For (1), the code pattern is correct. Sharing buffer1 is valid.
Moreover, you can use/share the same buffer if your code pattern is as follows:
cusparseDcsrilu02_analysis(..,**buffer1**);
cusparseDcsrilu02(..,**buffer1**);

cusparseSpSV_analysis(..,**buffer1**); // L
cusparseSpSV_solve(); // L

cusparseSpSV_analysis(..,**buffer1**); // U
cusparseSpSV_solve(); // U

For (2), yes it does use the allocated buffer. The buffer should not be reallocated between SpSV analysis and solve steps.

**Comment by jczhang07** [comment]
Thanks, that explains errors in my code.  I need to do multiple solves with the same L, U but different right hand sides. So I have to

```
cusparseSpSV_analysis(..,buffer1); // L
cusparseSpSV_analysis(..,buffer2); // U

// solve
cusparseSpSV_solve(); // L
cusparseSpSV_solve(); // U

// solve again
cusparseSpSV_solve(); // L
cusparseSpSV_solve(); // U
```

**Comment by malmasri7** [comment]
Yes, this is the common usage. Then, you need different buffers for L and U parts.
