### ISSUE TITLE
Is cusparseSpSV_analysis() symbolic or numeric?

### ISSUE THREAD

**Issue by jczhang07** [NVIDIA/CUDALibrarySamples#78]
https://github.com/NVIDIA/CUDALibrarySamples/blob/22d01d930423729489d4d10bd12986b6e8b01bf8/cuSPARSE/bicgstab/bicgstab_example.c#L223

I mean, can I call `cusparseSpSV_analysis()` with stale matrix values (but with correct sparsity pattern, i.e., row pointer and column indices), and when calling `cusparseSpSV_solve()`, I provide up-to-date matrix values?

**Comment by malmasri7** [comment]
Hello Junchao,
The analysis step is numeric. You need to call to the `cusparseSpSV_analysis()` for new matrix values.
