### ISSUE TITLE
cuTENSOR/contraction.cu is compiled successfully, but the object file doesn't work. 

### ISSUE THREAD

**Issue by Y-jiji** [NVIDIA/CUDALibrarySamples#79]
## Trouble
Compilation seems successful, but the 'contraction.exe' file doesn't give any output. 
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/71013200/177041713-16a0c735-5647-4d4a-a000-3f65638fc40e.png">

## OS
Windows 10 21H1

## NVCC

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Cuda compilation tools, release 11.7, V11.7.64

**Comment by nishqasharma** [comment]
Hey so you might want to check the compute capability of your GPU (I'm not sure if that is the problem, but it might be)--cutensor only works with compute capability 6.0 or greater, according to https://docs.nvidia.com/cuda/cutensor/user_guide.html 

You can use either the command line or the Windows PC settings to find out which GPU you have, and then check what the compute capability of your GPU is here: https://developer.nvidia.com/cuda-gpus

When I ran the code on the A100 (compute capability 8.0) it ran smoothly just by copy pasting the code on the website into a file and compiling and running it like you've done in your screnshot); but when I tried running it on RTX (compute capability 3.5), it ran partially and then threw a runtime error.

**Comment by v0i0** [comment]
Hi @Y-jiji ,

Are you still experiencing this issue? Typically, when you see no output it indicates an issue with your CUDA or compiler setup where some DLL cannot be found. Does any kind of message box pop up when you run the code?

To further assist you, it would be good to know what GPU you are trying to run on, which driver you are using, and what your PATH environment variable looks like.

**Comment by JanuszL** [comment]
Please reopen if this issue is still valid for you.
