### ISSUE TITLE
Extract main diagonal elements

### ISSUE THREAD

**Issue by hahapz** [NVIDIA/CUDALibrarySamples#8]
Hello, Is there a method to extract main diagonal elements of a sparse matrix in cusparse(the format I am using in cuSparse is CSR)? I want to use it as a preconditioner in my PCG algorithm. Looking forward to your reply!

**Comment by hahapz** [comment]
Let me describe my problem in detail.  
I have a sparse matrix J and a vector r, we need solve linear equation J'J x = J'b by using PCG algorithom. How can I extract 
the block diagonal elements or  main diagonal elements of the sparse matrix J'J to form a new matrix efficiently(the block size I need is 6*6)?

**Comment by federico-busato** [comment]
cuSPARSE does not provide this functionality yet. We will consider adding it in future releases. Thanks for the feedback

**Comment by fbusato** [comment]
cuSPARSE does not provide this functionality yet. We will consider adding it in future releases. Thanks for the feedback
