### ISSUE TITLE
How to trigger individual mode of batched cusparseSpmm

### ISSUE THREAD

**Issue by tlu7** [NVIDIA/CUDALibrarySamples#81]
cusparseSpMM() with all algorithms support the following batch modes except for CUSPARSE_SPMM_CSR_ALG3:

Ci = Ai Bi
Ci = A Bi
Ci = Ai B

The number of batches and their strides can be set by using cusparseCooSetStridedBatch, cusparseCsrSetStridedBatch, and cusparseDnMatSetStridedBatch.

How shall I trigger one of the three modes? Do A, B, and C require the same batch dimension even though A or B does not have a batch dimension?

https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spmm

**Comment by fbusato** [comment]
> How shall I trigger one of the three modes? Do A, B, and C require the same batch dimension even though A or B does not have a batch dimension?

yes, it is correct. A, B, and C must have the same batch size, while you can play with `batch_stride`

in case you missed it, the following example show the batched SpMM behavior https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSE/spmm_csr_batched

**Comment by tlu7** [comment]
Thanks for the quick response!

Can I use the following example to make sure I understand it?
 
For example, A is batched COO with shape [n_batch, 2, 3] and B is unbatched with shape [3, 4]. This is Ci = Ai B mode.

I would have to use the same batch_count `n_batch` in cusparseCooSetStridedBatch for A and cusparseDnMatSetStridedBatch for B and C. But the batch_stride of A is 2 * 3 whereas the batch_stride of B is n_batch * 3 * 4?

When I create B, do I need to create B with shape of [n_batch, 3, 4] by padding a lot of zeros?

**Comment by fbusato** [comment]
no, you don't need to pad the matrix B. You can just set `batch_stride = 0`

**Comment by tlu7** [comment]
Could you share some documentation on the batch_count and batch_stride behaviors in cusparseSpMM?

Can batch_count be zero, e.g. falling back to C = A B mode? Or batch_count > 0 is required?  

I also did not find the documentation for setting `batch_stride = 0 ` to trigger Ci = Ai B and Ci = A Bi modes.

`Address offset between a matrix and the next one in the batch. batchStride ≥ ld * cols if the matrix uses column-major layout, batchStride ≥ ld * rows otherwise`

**Comment by fbusato** [comment]
I just tested the sample with `batch_stride = 0` and I'm able to reproduce the same problem. It is an actual bug. The APIs should allow a value equal to 0. The fix will be available in the next major release. As a workaround, you can replicate the B and C matrix in the batch and use  `batch_stride = matrix size`

**Comment by tlu7** [comment]
Thanks. May I know the release version in which the update will be made?

**Comment by fbusato** [comment]
yes, it should be CUDA 12.0
