### ISSUE TITLE
nvJPEG performance severely reduced with multiple GPUs

### ISSUE THREAD

**Issue by michalsuchanek** [NVIDIA/CUDALibrarySamples#83]
I'm trying to do some nvJPEG encoding with a couple of 3080's and I'm seeing strange behavior - using two GPU's is about three times slower(!) than using just one. Specifically, I am running multiple instances of an encoding application in parallel (rather than multiple threads inside one program) and each of these instances runs cudaSetDevice when initializing. I can see it it works because Task Manager clearly shows that the assigned GPU(s) are doing the work. However, the actual encoding process runs much slower if I use both of the GPU's -  as I mentioned above, encoding the exact same input (55GB of RAW images) takes about 3x longer when I use both GPUs. Naturally, this is the opposite of what I expected. Am I overlooking something? Is there some system resource competition that is causing this slowdown? System config issue?

**Comment by maheshkha** [comment]
Hi [michalsuchanek](https://github.com/michalsuchanek)
Thank you for reporting this issue.
We have update the sample code. Can you verify the fix works for you?

**Comment by michalsuchanek** [comment]
Hi maheshkha,
Thanks for the update. I assume you're talking about the nvJPEG-Decoder-MultipleInstances example. Unfortunately, I'm not sure this pertains to my situation:
1) As I mentioned in my first post: I am running multiple instances of an encoding application in parallel (rather than multiple threads inside one program)
2) I am running two GPU's; the above example makes no mention of device assignment and seems to be intended to run on a single device.

What I'm looking to do is run two processes, each assigned to a different GPU and each encoding independent data streams in parallel. My nvjpeg encoder implementation is already multi-threaded; what I'm trying to determine is why running two instances - one per GPU - is slower than running one instance on one GPU.

Thank you for your time and attention on this issue.

**Comment by michalsuchanek** [comment]
(accidentally closed when posting above comment, disregard)

**Comment by trybicki-nv** [comment]
Hi, 

Not sure about your HW configuration. You mention running on two GPUs...but I would assume there is only one CPU?

A significant part of the encoding is synchronous, and happens on the host. So the bottleneck might be the CPU. Or - memory transfers (you mention 55GB of data). Have you looked into that?

**Comment by trybicki-nv** [comment]
No response, closing. Feel free to reopen if you have any more questions.
