### ISSUE TITLE
Column indices sortedness of cusparseSpGEMMreuse

### ISSUE THREAD

**Issue by jczhang07** [NVIDIA/CUDALibrarySamples#84]
Hello,
  In the sample [spgemm_reuse_example.c ](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuSPARSE/spgemm_reuse/spgemm_reuse_example.c), I assume after the second `cusparseSpGEMMreuse_copy()` at [line 227](https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuSPARSE/spgemm_reuse/spgemm_reuse_example.c#L227,) 
the structure of the output matrix C is known. 

Are column indices of C sorted? If not, can I sort them before calling `cusparseSpGEMMreuse_compute()`.  Note that `cusparseSpGEMMreuse_compute()` might be called multiple times with different A, B values.

Thank you.

**Comment by fbusato** [comment]
yes, it is correct. After `cusparseSpGEMMreuse_copy()` the structure of matrix C is known. You can assume that the column indices are sorted before `cusparseSpGEMMreuse_compute()`. 
`cusparseSpGEMMreuse_compute()` just computes the values. It does not affect the structure of C at all.

**Comment by jczhang07** [comment]
@fbusato 
cusparse doc (https://docs.nvidia.com/cuda/cusparse/index.html#csr-format) says "Both sorted and unsorted column indices are supported.".

From what you said, does it imply even if A, B might be unsorted, C is guaranteed to be sorted?

**Comment by fbusato** [comment]
yes, the link you provided is a general statement for the CSR format and it applies to all routines except the opposite is specified in the documentation of a specific routine

**Comment by jczhang07** [comment]
Thanks for the clarification.  I just did not find in the doc that [cusparseSpGEMMreuse()](https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spgemm-reuse) outputs sorted matrices.

**Comment by fbusato** [comment]
thanks, we will add this note to the documentation
