### ISSUE TITLE
nvjpeg  example of nvJPEGDecMultipleInstances,  CUDA Runtime failure

### ISSUE THREAD

**Issue by GxjGit** [NVIDIA/CUDALibrarySamples#85]
Cuda 11.7, V11.7.99
Tesla V100-SXM2
code:  CUDALibrarySamples/nvJPEG/nvJPEG-Decoder-MultipleInstances/

$ mkdir build
$ cd build
$ cmake ..
$ make
$ ./nvJPEGDecMultipleInstances  -i /imagenet/ -b 256 -j 16

errors ars as following: 

![image](https://user-images.githubusercontent.com/24288375/184794889-ff937e57-dfa2-4be9-a669-88fe81e87ade.png)

when num_threads,  the Parameter of -j,  is set bigger,   this error will occur more easiler.  when it is set to be 1,  it always be ok.

**Comment by maheshkha** [comment]
Hi GxjGit
Thank you for reporting this issue.
We have update the sample code. Can you verify the fix works for you?

**Comment by GxjGit** [comment]
> 



> Hi GxjGit Thank you for reporting this issue. We have update the sample code. Can you verify the fix works for you?

Thank you for your reply.  I have verified that it can run without any errors as expected.  But I have a new question, when i integrate it into the training process,  with an epoch trainning,  the top 5 Accuracy dropped from 28% to 20%  compared to decoding with pil in cpu.  My transforms.Compos is as following:
transforms.Compose(
        [
            transforms.RandomResizedCrop(224),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            normalize,
        ]
    ) 

Have you verified the convergence of the model after integrating this sample into the training process, or are there any methods and suggestions to locate this problem?
