### ISSUE TITLE
How to speed up batch encoder for jpeg ?

### ISSUE THREAD

**Issue by simpia** [NVIDIA/CUDALibrarySamples#89]
For small size pictures, is there a way to speed up encoding JPEG

**Comment by maheshkha** [comment]
Hi, Can you share more details about small size like HxW abd bit depth etc you are using?
How many batch of images? Are they are always same size or variable?

**Comment by simpia** [comment]
@maheshkha I use it to compress tile in tiff file. The size of a single tile is usually 240*240. Their size is the same, and the compression mode is the same. There are 20000 tiles in each group.

**Comment by maheshkha** [comment]
Hi @simpia 
Thank you for details.

You can set the encoder quality parameter and turn off the optimized huffman. This will save encoding time and improves the overall performance.
Example API
        CHECK_NVJPEG(nvjpegEncoderParamsSetQuality(nvjpeg_encode_params, **75**, NULL));
        CHECK_NVJPEG(nvjpegEncoderParamsSetOptimizedHuffman(nvjpeg_encode_params, 0, NULL));

Raw image data copy from Host to GPU is limiting some of encoding stages - it will benefits more for large image size.
