### ISSUE TITLE
windows10 && cuda10.2 编译失败

### ISSUE THREAD

**Issue by liushuan** [NVIDIA/CUDALibrarySamples#9]
1>nvjpegDecoder.cpp(40): error C2660: “cudaEventCreate”: 函数不接受 2 个参数
1>nvjpegDecoder.cpp(41): error C2660: “cudaEventCreate”: 函数不接受 2 个参数
1>nvjpegDecoder.cpp(56): error C3861: “nvjpegJpegStreamParseHeader”: 找不到标识符
1>nvjpegDecoder.cpp(58): error C3861: “nvjpegDecodeBatchedSupported”: 找不到标识符
1>nvjpegDecoder.cpp(84): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
1>nvjpegDecoder.cpp(331): error C2065: “NVJPEG_BACKEND_HARDWARE”: 未声明的标识符

**Comment by maheshkha** [comment]
Hi Liushuan,

A100 has dedicated HW decoder can be access through the NVJPEG_BACKEND_HARDWARE and only supports in CUDA 11.0 and above release.
 
Can you provide additional details on GPU configuration and CUDA driver?

**Comment by maheshkha** [comment]
From last comment use latest CUDA 11.0 and above.
Closing this issue.
