### ISSUE TITLE
cusparseSpMM COO batch mode computation and cuda version

### ISSUE THREAD

**Issue by tlu7** [NVIDIA/CUDALibrarySamples#91]
Hi, I have a test using `cusparseSpMM COO batch mode` bindings that passes on cuda 11.7 and fail on cuda 11.4/11.1. Is it possible that the batch mode support of cusparseSpmm differ between two different cuda versions?

**Comment by qanhpham** [comment]
Hi. Yes, the support for batched computation in cusparseSpMM COO was added in 11.6.1:
[https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cusparse-11.6.1](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cusparse-11.6.1)

**Comment by tlu7** [comment]
Thanks a lot for confirming!
