### ISSUE TITLE
spmma2 linker issue

### ISSUE THREAD

**Issue by dzdang** [NVIDIA/CUDALibrarySamples#92]
I'm trying to compile spmma2, but I'm seeing the below error
```
[.... ~/local/CUDALibrarySamples/cuSPARSELt/spmma2 (master)]$ make
nvcc --std=c++14 -I/usr/local/cuda-11.5/include -I/usr/local/cuda-11.5//include spmma2_example.cpp -o spmma2_example_static \
         -Xlinker=--whole-archive                                        \
         -Xlinker=/usr/local/cuda-11.5//lib64/libcusparseLt_static.a        \
         -Xlinker=--no-whole-archive                                     \
         -lcudart -lcusparse -ldl
/usr/local/cuda-11.5//lib64/libcusparseLt_static.a(init_kernels.cpp.o): In function `cask_cusparse::initialize_cuda_standalone_kernels(cask_cusparse::Manifest&)':
init_kernels.cpp:(.text+0x45): undefined reference to `cask_safe_cusparse::cutlass_cask_plugin::kernelInit(cask_cusparse::Manifest&)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:68: spmma2_example_static] Error 1
```

it looks like it can't find the definition, so that tells me something isn't being linked properly

can someone advise how to resolve? thanks

**Comment by qanhpham** [comment]
Hi. What version of cuSPARSELt are you using? Can you try the latest version v0.3.0 to see if you still have the issue?

**Comment by dzdang** [comment]
@qanhpham  hi. I am using the latest v0.3.0 version. Are there external variables I should be setting before trying to compile?

**Comment by qanhpham** [comment]
Hi @dzdang. Can you try this:

- Compile **spmma2_example.cpp** to object file **spmma2_example.o**
- Create executable: 
`nvcc spmma2_example.o -o spmma2_example_static -Wl,-rpath,/usr/local/cuda-11.4/lib64:/usr/local/cuda-11.4/targets/x86_64-linux/lib: ./libcusparseLt_static.a /usr/local/cuda-11.4/lib64/libcudart.so`

You may need to change the correct paths in your system.

**Comment by qanhpham** [comment]
Hi @dzdang. Have you solved the issue?

**Comment by dzdang** [comment]
Hi. I ended up integrating the example into pytorch, where I already set up the build system with cuSPARSELt dynamic libraries. I didn't try to compile the example directly from CUDALibrarySamples
