### ISSUE TITLE
Setting split K to value greater than 1 causes internal error.

### ISSUE THREAD

**Issue by chenfucn** [NVIDIA/CUDALibrarySamples#94]
It appears that if I set algo property CUSPARSELT_MATMUL_SPLIT_K to anything greater than 1, sparse Matmul would return 'internal error'

The following code executes normally if splitk = 1,  splitKMode = CUSPARSELT_SPLIT_K_MODE_ONE_KERNEL and splitBufs = 0;  But if I change splitk to 2 or 4, the subsequent matmul will return 'internal error'.

        CHECK_CUSPARSE(cusparseLtMatmulAlgSetAttribute(
                &handle, &alg_sel,
                CUSPARSELT_MATMUL_ALG_CONFIG_ID,
                &fast_algo, sizeof(fast_algo)))
        CHECK_CUSPARSE(cusparseLtMatmulAlgSetAttribute(
                &handle, &alg_sel,
                CUSPARSELT_MATMUL_SPLIT_K,
                &splitk, sizeof(splitk)))
        CHECK_CUSPARSE(cusparseLtMatmulAlgSetAttribute(
                &handle, &alg_sel,
                CUSPARSELT_MATMUL_SPLIT_K_MODE,
                &splitKMode, sizeof(splitKMode)))
        CHECK_CUSPARSE(cusparseLtMatmulAlgSetAttribute(
                &handle, &alg_sel,
                CUSPARSELT_MATMUL_SPLIT_K_BUFFERS,
                &splitBufs, sizeof(splitBufs)))
        CHECK_CUSPARSE(cusparseLtMatmulPlanInit(&handle, &plan, &matmul, &alg_sel, workspace_size))
        CHECK_CUSPARSE(cusparseLtMatmul(&handle, &plan, &alpha, dA_compressed, dB,
                    &beta, dC, dD, d_workspace, &(streams[0]), num_streams))

**Comment by qanhpham** [comment]
Hi @chenfucn. When splitK > 1, the splitBufs value has to be: 1 <= splitBufs < splitK.
The only case that splitBufs can be 0 is splitk = 1, splitKMode = CUSPARSELT_SPLIT_K_MODE_ONE_KERNEL (like in your 1st case).

**Comment by collinmccarthy** [comment]
@qanhpham Also related to this, the [cusparseLtMatmulSearch](https://docs.nvidia.com/cuda/cusparselt/functions.html#cusparseltmatmulsearch) section says 

"The function also searches for optimal combination of [Split-K parameters](https://docs.nvidia.com/cuda/cusparselt/types.html#cusparseltmatmulalgattribute-t-label) if CUSPARSELT_MATMUL_SPLIT_K is set to 0 prior the function call. The selected values can be retrieved by using [cusparseLtMatmulAlgGetAttribute()](https://docs.nvidia.com/cuda/cusparselt/functions.html#cusparseltmatmulalggetattribute-label)."

However I set `CUSPARSELT_MATMUL_SPLIT_K` to 0 I immediately get an error:
```
 ** On entry to cusparseLtMatmulAlgSetAttribute(): The splitK value must be greater than 0: 0
```

So I'm assuming I need to set `CUSPARSELT_MATMUL_SPLIT_K` to 1? That matches what is said in the [cusparseLtMatmulAlgAttribute_t](https://docs.nvidia.com/cuda/cusparselt/types.html?highlight=cusparselt_matmul_split_k#cusparseltmatmulalgattribute-t) docs.

**Comment by chenfucn** [comment]
@qanhpham 
2, 4, 1, 3 fails too.

**Comment by qanhpham** [comment]
Hi @collinmccarthy . Sorry, this is a mistake in the documentation. That statement isn't correct.
To run the matmul search, we need to initialize a new `cusparseLtMatmulAlgSelection_t`  variable, run `cusparseLtMatmulAlgSelectionInit` with it and do the search.
This has to be done each time we do the matmul search. We can't reuse `cusparseLtMatmulAlgSelection_t` between searches.

**Comment by collinmccarthy** [comment]
@qanhpham Thank you, it's working now.
