### ISSUE TITLE
[cuSPARSELt] Compressed Size / Compression Format

### ISSUE THREAD

**Issue by collinmccarthy** [NVIDIA/CUDALibrarySamples#95]
Hello,

I'm trying to figure out the cuSPARSELt compression "format" so I can potentially write my own pruning + compression kernel for my specific use case. However (a) I'm seeing inconsistent results in the compressed size (probably due to padding), and (b) I don't know the exact CSR-like compression format (but I could try a few things based on [the paper](https://arxiv.org/pdf/2104.08378.pdf) and maybe one of them would work).

Would it be possible for you to disclose the compression format / padding here, and put that in `cusparseLt.h` in a future update? The current pruning + compression algorithms work well for weight sparsity where the compression is done once and then re-used, but there are many other things one could do with cuSparseLt, and some of these would require real-time pruning + compression kernels, and without the compression format known we simply cannot write those. 

To be specific, if I run the `spmma2` example with `B=1, M=8, K=16`, I get the following, which does not match my expectations.

```console
>> compressed_size  // as requested by cusparseLt
384

>> b*m*(k/2)*2 + ((b*m*(k/2)*2)/8)  // as described in the paper, for half-precision
144
```

But if I run it with `B=1, M=1024, K=2048` I get the following, which does match my expecations.

```console
>> compressed_size  // as requested by cusparseLt
2359296

>> b*m*(k/2)*2 + ((b*m*(k/2)*2)/8)  // as described in the paper, for half-precision
2359296
```

Thank you in advance.

**Comment by fbusato** [comment]
Hi @collinmccarthy, unfortunately we cannot disclose the internal format. In addition, we use slightly different formats depending on the GPU arch. The pruning should be only applied to the dense matrix and then use cuSPARSELt utils to convert to the internal format. The conversion is pretty fast, and it takes less than 5% of the spmma computation, so this should not be a limitation.

**Comment by collinmccarthy** [comment]
Thank you @fbusato. For small matrices the overhead is more significant than 5%, I'll try to quantify this and update the issue.
