### ISSUE TITLE
CUSPARSE_SPMM_COO_ALG2 on column-major layout

### ISSUE THREAD

**Issue by tlu7** [NVIDIA/CUDALibrarySamples#97]
cusparse Spmm requires input of column-major layout while using CUSPARSE_SPMM_COO_ALG2.

We see the runtime failure below. However, this failure occurs on cuda 11.4 but not 11.8.  It is possible that the runtime error is due to something else?

```
(#define GPUSPARSE_SPMM_COO_ALG CUSPARSE_SPMM_COO_ALG2)
E   RuntimeError: [jaxlib/gpu/sparse.cc:538](https://cs.corp.google.com/piper///depot/google3/jaxlib/gpu/sparse.cc?l=538): operation gpusparseSpMM_bufferSize( handle.get(), op_A, GPUSPARSE_OPERATION_NON_TRANSPOSE, &alpha, mat_a, mat_b, &beta, mat_c, C.type, GPUSPARSE_SPMM_COO_ALG, &buffer_size) failed: invalid value
----------------------------- Captured stderr call -----------------------------
 ** On entry to cusparseSpMM_bufferSize(): matrix B must be in column-major order
```

**Comment by tlu7** [comment]
@jakevdp @fbusato

**Comment by qanhpham** [comment]
Hi @tlu7. Since cuSPARSE 11.7u1, COO SpMM supports row-major order for matrix B (and C): [11.7u1 release notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cusparse-11.7.1)

**Comment by tlu7** [comment]
Thanks a lot for the quick response!
